<?xml version='1.0'?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
       xmlns:in="http://www.posc.org/schemas" 
       xmlns:xs="http://www.w3.org/2001/XMLSchema"
       version="2.0">
    <xsl:output method="text"/>

<xsl:template match="/">
		
       <!-- Info -->	
       <xsl:text>#This file is generated by witsmlUnitToPython.xsl&#10;</xsl:text>
	   <xsl:text>#By Reading the WitsmlDict.xml&#10;</xsl:text>
	   <xsl:text>#Do not modify this file manually;&#10;</xsl:text>
	   <xsl:text>&#10;</xsl:text>
	   	
       <!-- imports -->	
       <xsl:text>import os&#10;</xsl:text>
       <xsl:text>import sys&#10;</xsl:text>   
       <xsl:text>import unitOfMeasure&#10;</xsl:text>            
       <xsl:text>&#10;</xsl:text>
       
	   <!-- main function -->
       <xsl:text>def buildUnitDict():&#10;</xsl:text>
       <xsl:text>&#10;</xsl:text>
       <xsl:text>    dictOfUnitOfMeasures = {}&#10;</xsl:text>
	   <xsl:text>&#10;</xsl:text>
       <xsl:apply-templates select="in:UnitOfMeasureDictionary"/>
	   <xsl:text>    return dictOfUnitOfMeasures</xsl:text>

       <xsl:text>&#10;</xsl:text>


</xsl:template>

<xsl:template match="in:UnitOfMeasureDictionary">
      <xsl:apply-templates select="in:UnitsDefinition"/>
</xsl:template>

<xsl:template match="in:UnitsDefinition">
      <xsl:apply-templates select="in:UnitOfMeasure"/>
</xsl:template>

<xsl:template match="in:UnitOfMeasure">
	<!--
    annotation = "m"
    conversion = unitOfMeasure.BaseConversion()  
    baseUnit = None     
    listOfQuantityTypes = ['length', 'breadth', 'depth', 'height', 'thickness', 'radius', 'radius of curvature', 'Cartesian coordinates', 'diameter', 'length of path', 'distance', 'wavelength', 'mean free path' ]
    unitOfMeasureObject = unitOfMeasure.UnitOfMeasure(annotation, "metre", listOfQuantityTypes, baseUnit, conversion)
    dictOfUnitOfMeasures[annotation] = unitOfMeasureObject
	-->
    <xsl:text>    annotation = "</xsl:text><xsl:value-of select="@annotation"/><xsl:text>"&#10;</xsl:text>
	<xsl:text>    name = "</xsl:text><xsl:value-of select="in:Name"/><xsl:text>"&#10;</xsl:text>
	<xsl:text>    DimensionalClass = "</xsl:text><xsl:value-of select="in:DimensionalClass"/><xsl:text>"&#10;</xsl:text>
	<xsl:text>    CatalogName = "</xsl:text><xsl:value-of select="in:CatalogName"/><xsl:text>"&#10;</xsl:text>
	<xsl:text>    CatalogSymbol = "</xsl:text><xsl:value-of select="in:CatalogSymbol"/><xsl:text>"&#10;</xsl:text>
    <xsl:choose>
		<xsl:when test="in:ConversionToBaseUnit">
		     <xsl:text>    baseUnit = "</xsl:text><xsl:value-of select="in:ConversionToBaseUnit/@baseUnit"/><xsl:text>"&#10;</xsl:text>
			 <xsl:choose>
			     <xsl:when test="in:ConversionToBaseUnit/in:Factor">
				      <xsl:text>    conversion = unitOfMeasure.FactorConversion("</xsl:text><xsl:value-of select="in:ConversionToBaseUnit/in:Factor"/><xsl:text>")&#10;</xsl:text>
				 </xsl:when>
			     <xsl:when test="in:ConversionToBaseUnit/in:Fraction">
				      <xsl:text>    conversion = unitOfMeasure.FractionConversion("</xsl:text>
					                  <xsl:value-of select="in:ConversionToBaseUnit/in:Fraction/in:Numerator"/><xsl:text>","</xsl:text>
									  <xsl:value-of select="in:ConversionToBaseUnit/in:Fraction/in:Denominator"/>
									  <xsl:text>")&#10;</xsl:text>
				 </xsl:when>
			     <xsl:when test="in:ConversionToBaseUnit/in:Formula">
				      <xsl:text>    conversion = unitOfMeasure.FormulaConversion("</xsl:text>
					                  <xsl:value-of select="in:ConversionToBaseUnit/in:Formula/in:A"/><xsl:text>","</xsl:text>
					                  <xsl:value-of select="in:ConversionToBaseUnit/in:Formula/in:B"/><xsl:text>","</xsl:text>
									  <xsl:value-of select="in:ConversionToBaseUnit/in:Formula/in:C"/><xsl:text>","</xsl:text>
									  <xsl:value-of select="in:ConversionToBaseUnit/in:Formula/in:D"/>
									  <xsl:text>")&#10;</xsl:text>
				 </xsl:when>
			 </xsl:choose>
		</xsl:when>
		<xsl:otherwise>
             <xsl:text>    baseUnit = None&#10;</xsl:text>
			 <xsl:text>    conversion = unitOfMeasure.BaseConversion()&#10;</xsl:text>
		</xsl:otherwise>
	</xsl:choose>

    <xsl:for-each select="in:QuantityType">
	    <xsl:choose>
		  <xsl:when test="position() = 1 and position() = last()">
		    <xsl:text>    listOfQuantityTypes = ["</xsl:text><xsl:value-of select="."/><xsl:text>"]&#10;</xsl:text>
		  </xsl:when>
		  <xsl:when test="position() = 1">
		    <xsl:text>    listOfQuantityTypes = ["</xsl:text><xsl:value-of select="."/><xsl:text>",</xsl:text>
		  </xsl:when>
		  <xsl:when test="position() = last()">
		     <xsl:text>"</xsl:text><xsl:value-of select="."/><xsl:text>"]&#10;</xsl:text> 
		  </xsl:when>
		  <xsl:when test="position() = last()">
		     <xsl:text>"</xsl:text><xsl:value-of select="."/><xsl:text>"]&#10;</xsl:text> 
		  </xsl:when>
		  <xsl:otherwise>
		     <xsl:text>"</xsl:text><xsl:value-of select="."/><xsl:text>",</xsl:text>
		  </xsl:otherwise>
		</xsl:choose>
	</xsl:for-each>

    <xsl:text>    SameUnitDict = {}&#10;</xsl:text>
	<xsl:for-each select="in:SameUnit">
		<!-- dict = {'Alice': '2341', 'Beth': '9102', 'Cecil': '3258'} -->
		<xsl:text>    SameUnitDict["</xsl:text><xsl:value-of select="@uom"/><xsl:text>"] = "</xsl:text><xsl:value-of select="@namingSystem"/><xsl:text>"&#10;</xsl:text>
	</xsl:for-each>
  
	<xsl:choose>
	   <xsl:when test="in:Deprecated">
	   		<xsl:text>    Deprecated = </xsl:text><xsl:value-of select="in:Deprecated"/><xsl:text>&#10;</xsl:text>
	   </xsl:when>
		<xsl:otherwise>
		    <xsl:text>    Deprecated = None&#10;</xsl:text>
		</xsl:otherwise>
	</xsl:choose>

    <xsl:text>    unitOfMeasureObject = unitOfMeasure.UnitOfMeasure(</xsl:text>
	              <xsl:text>annotation,</xsl:text>
				  <xsl:text>name,</xsl:text>
                  <xsl:text>listOfQuantityTypes,</xsl:text>
				  <xsl:text>baseUnit,</xsl:text>
				  <xsl:text>conversion,</xsl:text>
				  <xsl:text>DimensionalClass,</xsl:text>
				  <xsl:text>CatalogName,</xsl:text>
				  <xsl:text>CatalogSymbol,</xsl:text>
				  <xsl:text>SameUnitDict,</xsl:text>
				  <xsl:text>Deprecated)&#10;</xsl:text>

	<xsl:text>    dictOfUnitOfMeasures[annotation] = unitOfMeasureObject&#10;</xsl:text>

    <xsl:text>&#10;</xsl:text>

</xsl:template>



</xsl:stylesheet><!-- Stylus Studio meta-information - (c) 2004-2009. Progress Software Corporation. All rights reserved.

<metaInformation>
	<scenarios>
		<scenario default="yes" name="Scenario1" userelativepaths="yes" externalpreview="no" url="witsmlUnitDict.xml" htmlbaseurl="" outputurl="unitDictGenerated.py" processortype="saxon8" useresolver="yes" profilemode="0" profiledepth="" profilelength=""
		          urlprofilexml="" commandline="" additionalpath="" additionalclasspath="" postprocessortype="none" postprocesscommandline="" postprocessadditionalpath="" postprocessgeneratedext="" validateoutput="no" validator="internal"
		          customvalidator="">
			<advancedProp name="sInitialMode" value=""/>
			<advancedProp name="bXsltOneIsOkay" value="true"/>
			<advancedProp name="bSchemaAware" value="true"/>
			<advancedProp name="bXml11" value="false"/>
			<advancedProp name="iValidation" value="0"/>
			<advancedProp name="bExtensions" value="true"/>
			<advancedProp name="iWhitespace" value="0"/>
			<advancedProp name="sInitialTemplate" value=""/>
			<advancedProp name="bTinyTree" value="true"/>
			<advancedProp name="xsltVersion" value="2.0"/>
			<advancedProp name="bWarnings" value="true"/>
			<advancedProp name="bUseDTD" value="false"/>
			<advancedProp name="iErrorHandling" value="fatal"/>
		</scenario>
	</scenarios>
	<MapperMetaTag>
		<MapperInfo srcSchemaPathIsRelative="yes" srcSchemaInterpretAsXML="no" destSchemaPath="" destSchemaRoot="" destSchemaPathIsRelative="yes" destSchemaInterpretAsXML="no"/>
		<MapperBlockPosition></MapperBlockPosition>
		<TemplateContext></TemplateContext>
		<MapperFilter side="source"></MapperFilter>
	</MapperMetaTag>
</metaInformation>
-->