# .\_gml.py
# -*- coding: utf-8 -*-
# PyXB bindings for NM:c4f74fce23a2f49d6da683416eb2980bfced7e33
# Generated 2013-06-21 14:42:08.005000 by PyXB version 1.2.1
# Namespace http://www.opengis.net/gml/3.2 [xmlns:gml]

import pyxb
import pyxb.binding
import pyxb.binding.saxer
import io
import pyxb.utils.utility
import pyxb.utils.domutils
import sys

# Unique identifier for bindings created at the same time
_GenerationUID = pyxb.utils.utility.UniqueIdentifier('urn:uuid:9ff8bbae-daaa-11e2-b2e7-08002718187b')

# Import bindings for namespaces imported into schema
from . import _nsgroup

Namespace = pyxb.namespace.NamespaceForURI('http://www.opengis.net/gml/3.2', create_if_missing=True)
Namespace.configureCategories(['typeBinding', 'elementBinding'])
ModuleRecord = Namespace.lookupModuleRecordByUID(_GenerationUID, create_if_missing=True)
ModuleRecord._setModule(sys.modules[__name__])

def CreateFromDocument (xml_text, default_namespace=None, location_base=None):
    """Parse the given XML and use the document element to create a
    Python instance.
    
    @kw default_namespace The L{pyxb.Namespace} instance to use as the
    default namespace where there is no default namespace in scope.
    If unspecified or C{None}, the namespace of the module containing
    this function will be used.

    @keyword location_base: An object to be recorded as the base of all
    L{pyxb.utils.utility.Location} instances associated with events and
    objects handled by the parser.  You might pass the URI from which
    the document was obtained.
    """

    if pyxb.XMLStyle_saxer != pyxb._XMLStyle:
        dom = pyxb.utils.domutils.StringToDOM(xml_text)
        return CreateFromDOM(dom.documentElement)
    if default_namespace is None:
        default_namespace = Namespace.fallbackNamespace()
    saxer = pyxb.binding.saxer.make_parser(fallback_namespace=default_namespace, location_base=location_base)
    handler = saxer.getContentHandler()
    saxer.parse(io.StringIO(xml_text))
    instance = handler.rootObject()
    return instance

def CreateFromDOM (node, default_namespace=None):
    """Create a Python instance from the given DOM node.
    The node tag must correspond to an element declaration in this module.

    @deprecated: Forcing use of DOM interface is unnecessary; use L{CreateFromDocument}."""
    if default_namespace is None:
        default_namespace = Namespace.fallbackNamespace()
    return pyxb.binding.basis.element.AnyCreateFromDOM(node, default_namespace)

from _nsgroup import operationVersion # {http://www.opengis.net/gml/3.2}operationVersion
from _nsgroup import modifiedCoordinate # {http://www.opengis.net/gml/3.2}modifiedCoordinate
from _nsgroup import stringValue # {http://www.opengis.net/gml/3.2}stringValue
from _nsgroup import integerValue # {http://www.opengis.net/gml/3.2}integerValue
from _nsgroup import booleanValue # {http://www.opengis.net/gml/3.2}booleanValue
from _nsgroup import valueFile # {http://www.opengis.net/gml/3.2}valueFile
from _nsgroup import sourceDimensions # {http://www.opengis.net/gml/3.2}sourceDimensions
from _nsgroup import targetDimensions # {http://www.opengis.net/gml/3.2}targetDimensions
from _nsgroup import minimumOccurs # {http://www.opengis.net/gml/3.2}minimumOccurs
from _nsgroup import maximumOccurs # {http://www.opengis.net/gml/3.2}maximumOccurs
from _nsgroup import minimumValue # {http://www.opengis.net/gml/3.2}minimumValue
from _nsgroup import maximumValue # {http://www.opengis.net/gml/3.2}maximumValue
from _nsgroup import realizationEpoch # {http://www.opengis.net/gml/3.2}realizationEpoch
from _nsgroup import origin # {http://www.opengis.net/gml/3.2}origin
from _nsgroup import remarks # {http://www.opengis.net/gml/3.2}remarks
from _nsgroup import AbstractObject # {http://www.opengis.net/gml/3.2}AbstractObject
from _nsgroup import reversePropertyName # {http://www.opengis.net/gml/3.2}reversePropertyName
from _nsgroup import targetElement # {http://www.opengis.net/gml/3.2}targetElement
from _nsgroup import associationName # {http://www.opengis.net/gml/3.2}associationName
from _nsgroup import defaultCodeSpace # {http://www.opengis.net/gml/3.2}defaultCodeSpace
from _nsgroup import gmlProfileSchema # {http://www.opengis.net/gml/3.2}gmlProfileSchema
from _nsgroup import scope # {http://www.opengis.net/gml/3.2}scope
from _nsgroup import duration # {http://www.opengis.net/gml/3.2}duration
from _nsgroup import AbstractValue # {http://www.opengis.net/gml/3.2}AbstractValue
from _nsgroup import AbstractScalarValue # {http://www.opengis.net/gml/3.2}AbstractScalarValue
from _nsgroup import AbstractScalarValueList # {http://www.opengis.net/gml/3.2}AbstractScalarValueList
from _nsgroup import parameterValue # {http://www.opengis.net/gml/3.2}parameterValue
from _nsgroup import AbstractGeneralParameterValue # {http://www.opengis.net/gml/3.2}AbstractGeneralParameterValue
from _nsgroup import integerValueList # {http://www.opengis.net/gml/3.2}integerValueList
from _nsgroup import formula # {http://www.opengis.net/gml/3.2}formula
from _nsgroup import axisAbbrev # {http://www.opengis.net/gml/3.2}axisAbbrev
from _nsgroup import rangeSet # {http://www.opengis.net/gml/3.2}rangeSet
from _nsgroup import DataBlock # {http://www.opengis.net/gml/3.2}DataBlock
from _nsgroup import tupleList # {http://www.opengis.net/gml/3.2}tupleList
from _nsgroup import File # {http://www.opengis.net/gml/3.2}File
from _nsgroup import coverageFunction # {http://www.opengis.net/gml/3.2}coverageFunction
from _nsgroup import CoverageMappingRule # {http://www.opengis.net/gml/3.2}CoverageMappingRule
from _nsgroup import GridFunction # {http://www.opengis.net/gml/3.2}GridFunction
from _nsgroup import anchorDefinition # {http://www.opengis.net/gml/3.2}anchorDefinition
from _nsgroup import secondDefiningParameter # {http://www.opengis.net/gml/3.2}secondDefiningParameter
from _nsgroup import SecondDefiningParameter # {http://www.opengis.net/gml/3.2}SecondDefiningParameter
from _nsgroup import anchorPoint # {http://www.opengis.net/gml/3.2}anchorPoint
from _nsgroup import usesValue # {http://www.opengis.net/gml/3.2}usesValue
from _nsgroup import dmsAngleValue # {http://www.opengis.net/gml/3.2}dmsAngleValue
from _nsgroup import includesValue # {http://www.opengis.net/gml/3.2}includesValue
from _nsgroup import methodFormula # {http://www.opengis.net/gml/3.2}methodFormula
from _nsgroup import dmsAngle # {http://www.opengis.net/gml/3.2}dmsAngle
from _nsgroup import decimalMinutes # {http://www.opengis.net/gml/3.2}decimalMinutes
from _nsgroup import minutes # {http://www.opengis.net/gml/3.2}minutes
from _nsgroup import seconds # {http://www.opengis.net/gml/3.2}seconds
from _nsgroup import members # {http://www.opengis.net/gml/3.2}members
from _nsgroup import AbstractMetaData # {http://www.opengis.net/gml/3.2}AbstractMetaData
from _nsgroup import coordinates # {http://www.opengis.net/gml/3.2}coordinates
from _nsgroup import LocationKeyWord # {http://www.opengis.net/gml/3.2}LocationKeyWord
from _nsgroup import featureMembers # {http://www.opengis.net/gml/3.2}featureMembers
from _nsgroup import track # {http://www.opengis.net/gml/3.2}track
from _nsgroup import indirectEntry # {http://www.opengis.net/gml/3.2}indirectEntry
from _nsgroup import polygonPatches # {http://www.opengis.net/gml/3.2}polygonPatches
from _nsgroup import trianglePatches # {http://www.opengis.net/gml/3.2}trianglePatches
from _nsgroup import pointArrayProperty # {http://www.opengis.net/gml/3.2}pointArrayProperty
from _nsgroup import curveArrayProperty # {http://www.opengis.net/gml/3.2}curveArrayProperty
from _nsgroup import surfaceArrayProperty # {http://www.opengis.net/gml/3.2}surfaceArrayProperty
from _nsgroup import solidArrayProperty # {http://www.opengis.net/gml/3.2}solidArrayProperty
from _nsgroup import history # {http://www.opengis.net/gml/3.2}history
from _nsgroup import locationName # {http://www.opengis.net/gml/3.2}locationName
from _nsgroup import geometryMembers # {http://www.opengis.net/gml/3.2}geometryMembers
from _nsgroup import pointMembers # {http://www.opengis.net/gml/3.2}pointMembers
from _nsgroup import curveMembers # {http://www.opengis.net/gml/3.2}curveMembers
from _nsgroup import surfaceMembers # {http://www.opengis.net/gml/3.2}surfaceMembers
from _nsgroup import solidMembers # {http://www.opengis.net/gml/3.2}solidMembers
from _nsgroup import exterior # {http://www.opengis.net/gml/3.2}exterior
from _nsgroup import interior # {http://www.opengis.net/gml/3.2}interior
from _nsgroup import AbstractRing # {http://www.opengis.net/gml/3.2}AbstractRing
from _nsgroup import AbstractCurveSegment # {http://www.opengis.net/gml/3.2}AbstractCurveSegment
from _nsgroup import segments # {http://www.opengis.net/gml/3.2}segments
from _nsgroup import AffinePlacement # {http://www.opengis.net/gml/3.2}AffinePlacement
from _nsgroup import AbstractSurfacePatch # {http://www.opengis.net/gml/3.2}AbstractSurfacePatch
from _nsgroup import patches # {http://www.opengis.net/gml/3.2}patches
from _nsgroup import AbstractGML # {http://www.opengis.net/gml/3.2}AbstractGML
from _nsgroup import abstractInlineProperty # {http://www.opengis.net/gml/3.2}abstractInlineProperty
from _nsgroup import name # {http://www.opengis.net/gml/3.2}name
from _nsgroup import topoPointProperty # {http://www.opengis.net/gml/3.2}topoPointProperty
from _nsgroup import topoCurveProperty # {http://www.opengis.net/gml/3.2}topoCurveProperty
from _nsgroup import topoSurfaceProperty # {http://www.opengis.net/gml/3.2}topoSurfaceProperty
from _nsgroup import topoVolumeProperty # {http://www.opengis.net/gml/3.2}topoVolumeProperty
from _nsgroup import topoPrimitiveMembers # {http://www.opengis.net/gml/3.2}topoPrimitiveMembers
from _nsgroup import catalogSymbol # {http://www.opengis.net/gml/3.2}catalogSymbol
from _nsgroup import valueComponents # {http://www.opengis.net/gml/3.2}valueComponents
from _nsgroup import ParameterValue # {http://www.opengis.net/gml/3.2}ParameterValue
from _nsgroup import ParameterValueGroup # {http://www.opengis.net/gml/3.2}ParameterValueGroup
from _nsgroup import derivedCRSType # {http://www.opengis.net/gml/3.2}derivedCRSType
from _nsgroup import axisDirection # {http://www.opengis.net/gml/3.2}axisDirection
from _nsgroup import rangeMeaning # {http://www.opengis.net/gml/3.2}rangeMeaning
from _nsgroup import pixelInCell # {http://www.opengis.net/gml/3.2}pixelInCell
from _nsgroup import Null # {http://www.opengis.net/gml/3.2}Null
from _nsgroup import degrees # {http://www.opengis.net/gml/3.2}degrees
from _nsgroup import Bag # {http://www.opengis.net/gml/3.2}Bag
from _nsgroup import Array # {http://www.opengis.net/gml/3.2}Array
from _nsgroup import GenericMetaData # {http://www.opengis.net/gml/3.2}GenericMetaData
from _nsgroup import AbstractTimeSlice # {http://www.opengis.net/gml/3.2}AbstractTimeSlice
from _nsgroup import AbstractFeature # {http://www.opengis.net/gml/3.2}AbstractFeature
from _nsgroup import AbstractGeometry # {http://www.opengis.net/gml/3.2}AbstractGeometry
from _nsgroup import pos # {http://www.opengis.net/gml/3.2}pos
from _nsgroup import posList # {http://www.opengis.net/gml/3.2}posList
from _nsgroup import Envelope # {http://www.opengis.net/gml/3.2}Envelope
from _nsgroup import LinearRing # {http://www.opengis.net/gml/3.2}LinearRing
from _nsgroup import LineStringSegment # {http://www.opengis.net/gml/3.2}LineStringSegment
from _nsgroup import ArcString # {http://www.opengis.net/gml/3.2}ArcString
from _nsgroup import ArcStringByBulge # {http://www.opengis.net/gml/3.2}ArcStringByBulge
from _nsgroup import ArcByCenterPoint # {http://www.opengis.net/gml/3.2}ArcByCenterPoint
from _nsgroup import CubicSpline # {http://www.opengis.net/gml/3.2}CubicSpline
from _nsgroup import BSpline # {http://www.opengis.net/gml/3.2}BSpline
from _nsgroup import OffsetCurve # {http://www.opengis.net/gml/3.2}OffsetCurve
from _nsgroup import Clothoid # {http://www.opengis.net/gml/3.2}Clothoid
from _nsgroup import GeodesicString # {http://www.opengis.net/gml/3.2}GeodesicString
from _nsgroup import PolygonPatch # {http://www.opengis.net/gml/3.2}PolygonPatch
from _nsgroup import Triangle # {http://www.opengis.net/gml/3.2}Triangle
from _nsgroup import Rectangle # {http://www.opengis.net/gml/3.2}Rectangle
from _nsgroup import Ring # {http://www.opengis.net/gml/3.2}Ring
from _nsgroup import AbstractParametricCurveSurface # {http://www.opengis.net/gml/3.2}AbstractParametricCurveSurface
from _nsgroup import Shell # {http://www.opengis.net/gml/3.2}Shell
from _nsgroup import identifier # {http://www.opengis.net/gml/3.2}identifier
from _nsgroup import AbstractImplicitGeometry # {http://www.opengis.net/gml/3.2}AbstractImplicitGeometry
from _nsgroup import AbstractTimeObject # {http://www.opengis.net/gml/3.2}AbstractTimeObject
from _nsgroup import timePosition # {http://www.opengis.net/gml/3.2}timePosition
from _nsgroup import AbstractTopology # {http://www.opengis.net/gml/3.2}AbstractTopology
from _nsgroup import CompositeValue # {http://www.opengis.net/gml/3.2}CompositeValue
from _nsgroup import coordinateOperationAccuracy # {http://www.opengis.net/gml/3.2}coordinateOperationAccuracy
from _nsgroup import sourceCRS # {http://www.opengis.net/gml/3.2}sourceCRS
from _nsgroup import targetCRS # {http://www.opengis.net/gml/3.2}targetCRS
from _nsgroup import coordOperation # {http://www.opengis.net/gml/3.2}coordOperation
from _nsgroup import method # {http://www.opengis.net/gml/3.2}method
from _nsgroup import value # {http://www.opengis.net/gml/3.2}value
from _nsgroup import valueList # {http://www.opengis.net/gml/3.2}valueList
from _nsgroup import operationParameter # {http://www.opengis.net/gml/3.2}operationParameter
from _nsgroup import group # {http://www.opengis.net/gml/3.2}group
from _nsgroup import formulaCitation # {http://www.opengis.net/gml/3.2}formulaCitation
from _nsgroup import parameter # {http://www.opengis.net/gml/3.2}parameter
from _nsgroup import conversion # {http://www.opengis.net/gml/3.2}conversion
from _nsgroup import componentReferenceSystem # {http://www.opengis.net/gml/3.2}componentReferenceSystem
from _nsgroup import ellipsoidalCS # {http://www.opengis.net/gml/3.2}ellipsoidalCS
from _nsgroup import cartesianCS # {http://www.opengis.net/gml/3.2}cartesianCS
from _nsgroup import sphericalCS # {http://www.opengis.net/gml/3.2}sphericalCS
from _nsgroup import geodeticDatum # {http://www.opengis.net/gml/3.2}geodeticDatum
from _nsgroup import verticalCS # {http://www.opengis.net/gml/3.2}verticalCS
from _nsgroup import verticalDatum # {http://www.opengis.net/gml/3.2}verticalDatum
from _nsgroup import baseGeodeticCRS # {http://www.opengis.net/gml/3.2}baseGeodeticCRS
from _nsgroup import baseCRS # {http://www.opengis.net/gml/3.2}baseCRS
from _nsgroup import coordinateSystem # {http://www.opengis.net/gml/3.2}coordinateSystem
from _nsgroup import cylindricalCS # {http://www.opengis.net/gml/3.2}cylindricalCS
from _nsgroup import linearCS # {http://www.opengis.net/gml/3.2}linearCS
from _nsgroup import polarCS # {http://www.opengis.net/gml/3.2}polarCS
from _nsgroup import userDefinedCS # {http://www.opengis.net/gml/3.2}userDefinedCS
from _nsgroup import engineeringDatum # {http://www.opengis.net/gml/3.2}engineeringDatum
from _nsgroup import affineCS # {http://www.opengis.net/gml/3.2}affineCS
from _nsgroup import imageDatum # {http://www.opengis.net/gml/3.2}imageDatum
from _nsgroup import timeCS # {http://www.opengis.net/gml/3.2}timeCS
from _nsgroup import temporalDatum # {http://www.opengis.net/gml/3.2}temporalDatum
from _nsgroup import axis # {http://www.opengis.net/gml/3.2}axis
from _nsgroup import AbstractCoverage # {http://www.opengis.net/gml/3.2}AbstractCoverage
from _nsgroup import domainSet # {http://www.opengis.net/gml/3.2}domainSet
from _nsgroup import rangeParameters # {http://www.opengis.net/gml/3.2}rangeParameters
from _nsgroup import doubleOrNilReasonTupleList # {http://www.opengis.net/gml/3.2}doubleOrNilReasonTupleList
from _nsgroup import primeMeridian # {http://www.opengis.net/gml/3.2}primeMeridian
from _nsgroup import ellipsoid # {http://www.opengis.net/gml/3.2}ellipsoid
from _nsgroup import semiMajorAxis # {http://www.opengis.net/gml/3.2}semiMajorAxis
from _nsgroup import datumRef # {http://www.opengis.net/gml/3.2}datumRef
from _nsgroup import usesPrimeMeridian # {http://www.opengis.net/gml/3.2}usesPrimeMeridian
from _nsgroup import usesEllipsoid # {http://www.opengis.net/gml/3.2}usesEllipsoid
from _nsgroup import geodeticDatumRef # {http://www.opengis.net/gml/3.2}geodeticDatumRef
from _nsgroup import ellipsoidRef # {http://www.opengis.net/gml/3.2}ellipsoidRef
from _nsgroup import primeMeridianRef # {http://www.opengis.net/gml/3.2}primeMeridianRef
from _nsgroup import engineeringDatumRef # {http://www.opengis.net/gml/3.2}engineeringDatumRef
from _nsgroup import imageDatumRef # {http://www.opengis.net/gml/3.2}imageDatumRef
from _nsgroup import verticalDatumRef # {http://www.opengis.net/gml/3.2}verticalDatumRef
from _nsgroup import temporalDatumRef # {http://www.opengis.net/gml/3.2}temporalDatumRef
from _nsgroup import coordinateOperationRef # {http://www.opengis.net/gml/3.2}coordinateOperationRef
from _nsgroup import singleOperationRef # {http://www.opengis.net/gml/3.2}singleOperationRef
from _nsgroup import operationRef # {http://www.opengis.net/gml/3.2}operationRef
from _nsgroup import generalConversionRef # {http://www.opengis.net/gml/3.2}generalConversionRef
from _nsgroup import generalTransformationRef # {http://www.opengis.net/gml/3.2}generalTransformationRef
from _nsgroup import usesSingleOperation # {http://www.opengis.net/gml/3.2}usesSingleOperation
from _nsgroup import concatenatedOperationRef # {http://www.opengis.net/gml/3.2}concatenatedOperationRef
from _nsgroup import usesOperation # {http://www.opengis.net/gml/3.2}usesOperation
from _nsgroup import passThroughOperationRef # {http://www.opengis.net/gml/3.2}passThroughOperationRef
from _nsgroup import usesMethod # {http://www.opengis.net/gml/3.2}usesMethod
from _nsgroup import conversionRef # {http://www.opengis.net/gml/3.2}conversionRef
from _nsgroup import transformationRef # {http://www.opengis.net/gml/3.2}transformationRef
from _nsgroup import valueOfParameter # {http://www.opengis.net/gml/3.2}valueOfParameter
from _nsgroup import valuesOfGroup # {http://www.opengis.net/gml/3.2}valuesOfGroup
from _nsgroup import usesParameter # {http://www.opengis.net/gml/3.2}usesParameter
from _nsgroup import operationMethodRef # {http://www.opengis.net/gml/3.2}operationMethodRef
from _nsgroup import abstractGeneralOperationParameterRef # {http://www.opengis.net/gml/3.2}abstractGeneralOperationParameterRef
from _nsgroup import operationParameterRef # {http://www.opengis.net/gml/3.2}operationParameterRef
from _nsgroup import includesParameter # {http://www.opengis.net/gml/3.2}includesParameter
from _nsgroup import operationParameterGroupRef # {http://www.opengis.net/gml/3.2}operationParameterGroupRef
from _nsgroup import referenceSystemRef # {http://www.opengis.net/gml/3.2}referenceSystemRef
from _nsgroup import crsRef # {http://www.opengis.net/gml/3.2}crsRef
from _nsgroup import coordinateSystemAxisRef # {http://www.opengis.net/gml/3.2}coordinateSystemAxisRef
from _nsgroup import usesAxis # {http://www.opengis.net/gml/3.2}usesAxis
from _nsgroup import coordinateSystemRef # {http://www.opengis.net/gml/3.2}coordinateSystemRef
from _nsgroup import ellipsoidalCSRef # {http://www.opengis.net/gml/3.2}ellipsoidalCSRef
from _nsgroup import cartesianCSRef # {http://www.opengis.net/gml/3.2}cartesianCSRef
from _nsgroup import verticalCSRef # {http://www.opengis.net/gml/3.2}verticalCSRef
from _nsgroup import temporalCSRef # {http://www.opengis.net/gml/3.2}temporalCSRef
from _nsgroup import linearCSRef # {http://www.opengis.net/gml/3.2}linearCSRef
from _nsgroup import userDefinedCSRef # {http://www.opengis.net/gml/3.2}userDefinedCSRef
from _nsgroup import sphericalCSRef # {http://www.opengis.net/gml/3.2}sphericalCSRef
from _nsgroup import polarCSRef # {http://www.opengis.net/gml/3.2}polarCSRef
from _nsgroup import cylindricalCSRef # {http://www.opengis.net/gml/3.2}cylindricalCSRef
from _nsgroup import obliqueCartesianCSRef # {http://www.opengis.net/gml/3.2}obliqueCartesianCSRef
from _nsgroup import singleCRSRef # {http://www.opengis.net/gml/3.2}singleCRSRef
from _nsgroup import definedByConversion # {http://www.opengis.net/gml/3.2}definedByConversion
from _nsgroup import includesSingleCRS # {http://www.opengis.net/gml/3.2}includesSingleCRS
from _nsgroup import compoundCRSRef # {http://www.opengis.net/gml/3.2}compoundCRSRef
from _nsgroup import usesEllipsoidalCS # {http://www.opengis.net/gml/3.2}usesEllipsoidalCS
from _nsgroup import usesCartesianCS # {http://www.opengis.net/gml/3.2}usesCartesianCS
from _nsgroup import usesSphericalCS # {http://www.opengis.net/gml/3.2}usesSphericalCS
from _nsgroup import usesGeodeticDatum # {http://www.opengis.net/gml/3.2}usesGeodeticDatum
from _nsgroup import usesVerticalCS # {http://www.opengis.net/gml/3.2}usesVerticalCS
from _nsgroup import usesVerticalDatum # {http://www.opengis.net/gml/3.2}usesVerticalDatum
from _nsgroup import verticalCRSRef # {http://www.opengis.net/gml/3.2}verticalCRSRef
from _nsgroup import baseGeographicCRS # {http://www.opengis.net/gml/3.2}baseGeographicCRS
from _nsgroup import projectedCRSRef # {http://www.opengis.net/gml/3.2}projectedCRSRef
from _nsgroup import usesCS # {http://www.opengis.net/gml/3.2}usesCS
from _nsgroup import derivedCRSRef # {http://www.opengis.net/gml/3.2}derivedCRSRef
from _nsgroup import usesEngineeringDatum # {http://www.opengis.net/gml/3.2}usesEngineeringDatum
from _nsgroup import engineeringCRSRef # {http://www.opengis.net/gml/3.2}engineeringCRSRef
from _nsgroup import usesAffineCS # {http://www.opengis.net/gml/3.2}usesAffineCS
from _nsgroup import usesImageDatum # {http://www.opengis.net/gml/3.2}usesImageDatum
from _nsgroup import usesObliqueCartesianCS # {http://www.opengis.net/gml/3.2}usesObliqueCartesianCS
from _nsgroup import imageCRSRef # {http://www.opengis.net/gml/3.2}imageCRSRef
from _nsgroup import usesTimeCS # {http://www.opengis.net/gml/3.2}usesTimeCS
from _nsgroup import usesTemporalCS # {http://www.opengis.net/gml/3.2}usesTemporalCS
from _nsgroup import usesTemporalDatum # {http://www.opengis.net/gml/3.2}usesTemporalDatum
from _nsgroup import temporalCRSRef # {http://www.opengis.net/gml/3.2}temporalCRSRef
from _nsgroup import geographicCRSRef # {http://www.opengis.net/gml/3.2}geographicCRSRef
from _nsgroup import geocentricCRSRef # {http://www.opengis.net/gml/3.2}geocentricCRSRef
from _nsgroup import member # {http://www.opengis.net/gml/3.2}member
from _nsgroup import metaDataProperty # {http://www.opengis.net/gml/3.2}metaDataProperty
from _nsgroup import pointRep # {http://www.opengis.net/gml/3.2}pointRep
from _nsgroup import location # {http://www.opengis.net/gml/3.2}location
from _nsgroup import LocationString # {http://www.opengis.net/gml/3.2}LocationString
from _nsgroup import featureMember # {http://www.opengis.net/gml/3.2}featureMember
from _nsgroup import featureProperty # {http://www.opengis.net/gml/3.2}featureProperty
from _nsgroup import AbstractFeatureCollection # {http://www.opengis.net/gml/3.2}AbstractFeatureCollection
from _nsgroup import definitionMember # {http://www.opengis.net/gml/3.2}definitionMember
from _nsgroup import definitionRef # {http://www.opengis.net/gml/3.2}definitionRef
from _nsgroup import MappingRule # {http://www.opengis.net/gml/3.2}MappingRule
from _nsgroup import centerOf # {http://www.opengis.net/gml/3.2}centerOf
from _nsgroup import position # {http://www.opengis.net/gml/3.2}position
from _nsgroup import extentOf # {http://www.opengis.net/gml/3.2}extentOf
from _nsgroup import edgeOf # {http://www.opengis.net/gml/3.2}edgeOf
from _nsgroup import centerLineOf # {http://www.opengis.net/gml/3.2}centerLineOf
from _nsgroup import multiLocation # {http://www.opengis.net/gml/3.2}multiLocation
from _nsgroup import multiCenterOf # {http://www.opengis.net/gml/3.2}multiCenterOf
from _nsgroup import multiPosition # {http://www.opengis.net/gml/3.2}multiPosition
from _nsgroup import multiCenterLineOf # {http://www.opengis.net/gml/3.2}multiCenterLineOf
from _nsgroup import multiEdgeOf # {http://www.opengis.net/gml/3.2}multiEdgeOf
from _nsgroup import multiCoverage # {http://www.opengis.net/gml/3.2}multiCoverage
from _nsgroup import multiExtentOf # {http://www.opengis.net/gml/3.2}multiExtentOf
from _nsgroup import multiPointDomain # {http://www.opengis.net/gml/3.2}multiPointDomain
from _nsgroup import multiCurveDomain # {http://www.opengis.net/gml/3.2}multiCurveDomain
from _nsgroup import multiSurfaceDomain # {http://www.opengis.net/gml/3.2}multiSurfaceDomain
from _nsgroup import multiSolidDomain # {http://www.opengis.net/gml/3.2}multiSolidDomain
from _nsgroup import gridDomain # {http://www.opengis.net/gml/3.2}gridDomain
from _nsgroup import rectifiedGridDomain # {http://www.opengis.net/gml/3.2}rectifiedGridDomain
from _nsgroup import generalOperationParameter # {http://www.opengis.net/gml/3.2}generalOperationParameter
from _nsgroup import MovingObjectStatus # {http://www.opengis.net/gml/3.2}MovingObjectStatus
from _nsgroup import status # {http://www.opengis.net/gml/3.2}status
from _nsgroup import statusReference # {http://www.opengis.net/gml/3.2}statusReference
from _nsgroup import topoComplexProperty # {http://www.opengis.net/gml/3.2}topoComplexProperty
from _nsgroup import multiPointProperty # {http://www.opengis.net/gml/3.2}multiPointProperty
from _nsgroup import multiCurveProperty # {http://www.opengis.net/gml/3.2}multiCurveProperty
from _nsgroup import multiSurfaceProperty # {http://www.opengis.net/gml/3.2}multiSurfaceProperty
from _nsgroup import multiSolidProperty # {http://www.opengis.net/gml/3.2}multiSolidProperty
from _nsgroup import multiGeometryProperty # {http://www.opengis.net/gml/3.2}multiGeometryProperty
from _nsgroup import Definition # {http://www.opengis.net/gml/3.2}Definition
from _nsgroup import dictionaryEntry # {http://www.opengis.net/gml/3.2}dictionaryEntry
from _nsgroup import direction # {http://www.opengis.net/gml/3.2}direction
from _nsgroup import dataSource # {http://www.opengis.net/gml/3.2}dataSource
from _nsgroup import dataSourceReference # {http://www.opengis.net/gml/3.2}dataSourceReference
from _nsgroup import DynamicFeature # {http://www.opengis.net/gml/3.2}DynamicFeature
from _nsgroup import dynamicMembers # {http://www.opengis.net/gml/3.2}dynamicMembers
from _nsgroup import boundedBy # {http://www.opengis.net/gml/3.2}boundedBy
from _nsgroup import EnvelopeWithTimePeriod # {http://www.opengis.net/gml/3.2}EnvelopeWithTimePeriod
from _nsgroup import locationReference # {http://www.opengis.net/gml/3.2}locationReference
from _nsgroup import AbstractGeometricAggregate # {http://www.opengis.net/gml/3.2}AbstractGeometricAggregate
from _nsgroup import geometryMember # {http://www.opengis.net/gml/3.2}geometryMember
from _nsgroup import pointMember # {http://www.opengis.net/gml/3.2}pointMember
from _nsgroup import solidMember # {http://www.opengis.net/gml/3.2}solidMember
from _nsgroup import vector # {http://www.opengis.net/gml/3.2}vector
from _nsgroup import AbstractGeometricPrimitive # {http://www.opengis.net/gml/3.2}AbstractGeometricPrimitive
from _nsgroup import pointProperty # {http://www.opengis.net/gml/3.2}pointProperty
from _nsgroup import curveProperty # {http://www.opengis.net/gml/3.2}curveProperty
from _nsgroup import surfaceProperty # {http://www.opengis.net/gml/3.2}surfaceProperty
from _nsgroup import GeometricComplex # {http://www.opengis.net/gml/3.2}GeometricComplex
from _nsgroup import baseCurve # {http://www.opengis.net/gml/3.2}baseCurve
from _nsgroup import Arc # {http://www.opengis.net/gml/3.2}Arc
from _nsgroup import ArcByBulge # {http://www.opengis.net/gml/3.2}ArcByBulge
from _nsgroup import CircleByCenterPoint # {http://www.opengis.net/gml/3.2}CircleByCenterPoint
from _nsgroup import Bezier # {http://www.opengis.net/gml/3.2}Bezier
from _nsgroup import Geodesic # {http://www.opengis.net/gml/3.2}Geodesic
from _nsgroup import baseSurface # {http://www.opengis.net/gml/3.2}baseSurface
from _nsgroup import curveMember # {http://www.opengis.net/gml/3.2}curveMember
from _nsgroup import AbstractGriddedSurface # {http://www.opengis.net/gml/3.2}AbstractGriddedSurface
from _nsgroup import solidProperty # {http://www.opengis.net/gml/3.2}solidProperty
from _nsgroup import surfaceMember # {http://www.opengis.net/gml/3.2}surfaceMember
from _nsgroup import abstractAssociationRole # {http://www.opengis.net/gml/3.2}abstractAssociationRole
from _nsgroup import abstractStrictAssociationRole # {http://www.opengis.net/gml/3.2}abstractStrictAssociationRole
from _nsgroup import abstractReference # {http://www.opengis.net/gml/3.2}abstractReference
from _nsgroup import description # {http://www.opengis.net/gml/3.2}description
from _nsgroup import descriptionReference # {http://www.opengis.net/gml/3.2}descriptionReference
from _nsgroup import Grid # {http://www.opengis.net/gml/3.2}Grid
from _nsgroup import measure # {http://www.opengis.net/gml/3.2}measure
from _nsgroup import Observation # {http://www.opengis.net/gml/3.2}Observation
from _nsgroup import using # {http://www.opengis.net/gml/3.2}using
from _nsgroup import target # {http://www.opengis.net/gml/3.2}target
from _nsgroup import subject # {http://www.opengis.net/gml/3.2}subject
from _nsgroup import resultOf # {http://www.opengis.net/gml/3.2}resultOf
from _nsgroup import domainOfValidity # {http://www.opengis.net/gml/3.2}domainOfValidity
from _nsgroup import AbstractTimePrimitive # {http://www.opengis.net/gml/3.2}AbstractTimePrimitive
from _nsgroup import validTime # {http://www.opengis.net/gml/3.2}validTime
from _nsgroup import AbstractTimeComplex # {http://www.opengis.net/gml/3.2}AbstractTimeComplex
from _nsgroup import timeInterval # {http://www.opengis.net/gml/3.2}timeInterval
from _nsgroup import AbstractTopoPrimitive # {http://www.opengis.net/gml/3.2}AbstractTopoPrimitive
from _nsgroup import directedNode # {http://www.opengis.net/gml/3.2}directedNode
from _nsgroup import directedEdge # {http://www.opengis.net/gml/3.2}directedEdge
from _nsgroup import directedFace # {http://www.opengis.net/gml/3.2}directedFace
from _nsgroup import directedTopoSolid # {http://www.opengis.net/gml/3.2}directedTopoSolid
from _nsgroup import TopoPoint # {http://www.opengis.net/gml/3.2}TopoPoint
from _nsgroup import TopoCurve # {http://www.opengis.net/gml/3.2}TopoCurve
from _nsgroup import TopoSurface # {http://www.opengis.net/gml/3.2}TopoSurface
from _nsgroup import TopoVolume # {http://www.opengis.net/gml/3.2}TopoVolume
from _nsgroup import TopoComplex # {http://www.opengis.net/gml/3.2}TopoComplex
from _nsgroup import subComplex # {http://www.opengis.net/gml/3.2}subComplex
from _nsgroup import superComplex # {http://www.opengis.net/gml/3.2}superComplex
from _nsgroup import maximalComplex # {http://www.opengis.net/gml/3.2}maximalComplex
from _nsgroup import topoPrimitiveMember # {http://www.opengis.net/gml/3.2}topoPrimitiveMember
from _nsgroup import unitOfMeasure # {http://www.opengis.net/gml/3.2}unitOfMeasure
from _nsgroup import quantityType # {http://www.opengis.net/gml/3.2}quantityType
from _nsgroup import quantityTypeReference # {http://www.opengis.net/gml/3.2}quantityTypeReference
from _nsgroup import Boolean_ as Boolean # {http://www.opengis.net/gml/3.2}Boolean
from _nsgroup import BooleanList # {http://www.opengis.net/gml/3.2}BooleanList
from _nsgroup import Category # {http://www.opengis.net/gml/3.2}Category
from _nsgroup import Count # {http://www.opengis.net/gml/3.2}Count
from _nsgroup import CountList # {http://www.opengis.net/gml/3.2}CountList
from _nsgroup import valueProperty # {http://www.opengis.net/gml/3.2}valueProperty
from _nsgroup import valueComponent # {http://www.opengis.net/gml/3.2}valueComponent
from _nsgroup import ValueArray # {http://www.opengis.net/gml/3.2}ValueArray
from _nsgroup import AbstractDiscreteCoverage # {http://www.opengis.net/gml/3.2}AbstractDiscreteCoverage
from _nsgroup import AbstractContinuousCoverage # {http://www.opengis.net/gml/3.2}AbstractContinuousCoverage
from _nsgroup import MultiPointCoverage # {http://www.opengis.net/gml/3.2}MultiPointCoverage
from _nsgroup import MultiCurveCoverage # {http://www.opengis.net/gml/3.2}MultiCurveCoverage
from _nsgroup import MultiSurfaceCoverage # {http://www.opengis.net/gml/3.2}MultiSurfaceCoverage
from _nsgroup import MultiSolidCoverage # {http://www.opengis.net/gml/3.2}MultiSolidCoverage
from _nsgroup import GridCoverage # {http://www.opengis.net/gml/3.2}GridCoverage
from _nsgroup import RectifiedGridCoverage # {http://www.opengis.net/gml/3.2}RectifiedGridCoverage
from _nsgroup import greenwichLongitude # {http://www.opengis.net/gml/3.2}greenwichLongitude
from _nsgroup import priorityLocation # {http://www.opengis.net/gml/3.2}priorityLocation
from _nsgroup import FeatureCollection # {http://www.opengis.net/gml/3.2}FeatureCollection
from _nsgroup import DefinitionCollection # {http://www.opengis.net/gml/3.2}DefinitionCollection
from _nsgroup import DefinitionProxy # {http://www.opengis.net/gml/3.2}DefinitionProxy
from _nsgroup import Dictionary # {http://www.opengis.net/gml/3.2}Dictionary
from _nsgroup import DynamicFeatureCollection # {http://www.opengis.net/gml/3.2}DynamicFeatureCollection
from _nsgroup import MultiGeometry # {http://www.opengis.net/gml/3.2}MultiGeometry
from _nsgroup import MultiPoint # {http://www.opengis.net/gml/3.2}MultiPoint
from _nsgroup import MultiCurve # {http://www.opengis.net/gml/3.2}MultiCurve
from _nsgroup import MultiSurface # {http://www.opengis.net/gml/3.2}MultiSurface
from _nsgroup import MultiSolid # {http://www.opengis.net/gml/3.2}MultiSolid
from _nsgroup import Point # {http://www.opengis.net/gml/3.2}Point
from _nsgroup import AbstractCurve # {http://www.opengis.net/gml/3.2}AbstractCurve
from _nsgroup import AbstractSurface # {http://www.opengis.net/gml/3.2}AbstractSurface
from _nsgroup import Circle # {http://www.opengis.net/gml/3.2}Circle
from _nsgroup import Cone # {http://www.opengis.net/gml/3.2}Cone
from _nsgroup import Cylinder # {http://www.opengis.net/gml/3.2}Cylinder
from _nsgroup import Sphere # {http://www.opengis.net/gml/3.2}Sphere
from _nsgroup import AbstractSolid # {http://www.opengis.net/gml/3.2}AbstractSolid
from _nsgroup import RectifiedGrid # {http://www.opengis.net/gml/3.2}RectifiedGrid
from _nsgroup import angle # {http://www.opengis.net/gml/3.2}angle
from _nsgroup import DirectedObservation # {http://www.opengis.net/gml/3.2}DirectedObservation
from _nsgroup import AbstractTimeGeometricPrimitive # {http://www.opengis.net/gml/3.2}AbstractTimeGeometricPrimitive
from _nsgroup import TimeReferenceSystem # {http://www.opengis.net/gml/3.2}TimeReferenceSystem
from _nsgroup import TimeCalendarEra # {http://www.opengis.net/gml/3.2}TimeCalendarEra
from _nsgroup import TimeOrdinalEra # {http://www.opengis.net/gml/3.2}TimeOrdinalEra
from _nsgroup import AbstractTimeTopologyPrimitive # {http://www.opengis.net/gml/3.2}AbstractTimeTopologyPrimitive
from _nsgroup import TimeTopologyComplex # {http://www.opengis.net/gml/3.2}TimeTopologyComplex
from _nsgroup import Node # {http://www.opengis.net/gml/3.2}Node
from _nsgroup import Edge # {http://www.opengis.net/gml/3.2}Edge
from _nsgroup import Face # {http://www.opengis.net/gml/3.2}Face
from _nsgroup import TopoSolid # {http://www.opengis.net/gml/3.2}TopoSolid
from _nsgroup import UnitDefinition # {http://www.opengis.net/gml/3.2}UnitDefinition
from _nsgroup import derivationUnitTerm # {http://www.opengis.net/gml/3.2}derivationUnitTerm
from _nsgroup import conversionToPreferredUnit # {http://www.opengis.net/gml/3.2}conversionToPreferredUnit
from _nsgroup import roughConversionToPreferredUnit # {http://www.opengis.net/gml/3.2}roughConversionToPreferredUnit
from _nsgroup import CategoryList # {http://www.opengis.net/gml/3.2}CategoryList
from _nsgroup import Quantity # {http://www.opengis.net/gml/3.2}Quantity
from _nsgroup import QuantityList # {http://www.opengis.net/gml/3.2}QuantityList
from _nsgroup import CountExtent # {http://www.opengis.net/gml/3.2}CountExtent
from _nsgroup import AbstractCoordinateOperation # {http://www.opengis.net/gml/3.2}AbstractCoordinateOperation
from _nsgroup import AbstractSingleOperation # {http://www.opengis.net/gml/3.2}AbstractSingleOperation
from _nsgroup import OperationMethod # {http://www.opengis.net/gml/3.2}OperationMethod
from _nsgroup import AbstractGeneralOperationParameter # {http://www.opengis.net/gml/3.2}AbstractGeneralOperationParameter
from _nsgroup import AbstractSingleCRS # {http://www.opengis.net/gml/3.2}AbstractSingleCRS
from _nsgroup import CoordinateSystemAxis # {http://www.opengis.net/gml/3.2}CoordinateSystemAxis
from _nsgroup import AbstractCoordinateSystem # {http://www.opengis.net/gml/3.2}AbstractCoordinateSystem
from _nsgroup import AbstractDatum # {http://www.opengis.net/gml/3.2}AbstractDatum
from _nsgroup import Ellipsoid # {http://www.opengis.net/gml/3.2}Ellipsoid
from _nsgroup import PrimeMeridian # {http://www.opengis.net/gml/3.2}PrimeMeridian
from _nsgroup import AbstractOperation # {http://www.opengis.net/gml/3.2}AbstractOperation
from _nsgroup import LineString # {http://www.opengis.net/gml/3.2}LineString
from _nsgroup import Polygon # {http://www.opengis.net/gml/3.2}Polygon
from _nsgroup import CompositeCurve # {http://www.opengis.net/gml/3.2}CompositeCurve
from _nsgroup import CompositeSurface # {http://www.opengis.net/gml/3.2}CompositeSurface
from _nsgroup import CompositeSolid # {http://www.opengis.net/gml/3.2}CompositeSolid
from _nsgroup import Curve # {http://www.opengis.net/gml/3.2}Curve
from _nsgroup import OrientableCurve # {http://www.opengis.net/gml/3.2}OrientableCurve
from _nsgroup import Surface # {http://www.opengis.net/gml/3.2}Surface
from _nsgroup import OrientableSurface # {http://www.opengis.net/gml/3.2}OrientableSurface
from _nsgroup import PolyhedralSurface # {http://www.opengis.net/gml/3.2}PolyhedralSurface
from _nsgroup import TriangulatedSurface # {http://www.opengis.net/gml/3.2}TriangulatedSurface
from _nsgroup import Solid # {http://www.opengis.net/gml/3.2}Solid
from _nsgroup import DirectedObservationAtDistance # {http://www.opengis.net/gml/3.2}DirectedObservationAtDistance
from _nsgroup import AbstractCRS # {http://www.opengis.net/gml/3.2}AbstractCRS
from _nsgroup import TimeInstant # {http://www.opengis.net/gml/3.2}TimeInstant
from _nsgroup import TimePeriod # {http://www.opengis.net/gml/3.2}TimePeriod
from _nsgroup import TimeCoordinateSystem # {http://www.opengis.net/gml/3.2}TimeCoordinateSystem
from _nsgroup import TimeCalendar # {http://www.opengis.net/gml/3.2}TimeCalendar
from _nsgroup import TimeClock # {http://www.opengis.net/gml/3.2}TimeClock
from _nsgroup import TimeOrdinalReferenceSystem # {http://www.opengis.net/gml/3.2}TimeOrdinalReferenceSystem
from _nsgroup import TimeNode # {http://www.opengis.net/gml/3.2}TimeNode
from _nsgroup import TimeEdge # {http://www.opengis.net/gml/3.2}TimeEdge
from _nsgroup import BaseUnit # {http://www.opengis.net/gml/3.2}BaseUnit
from _nsgroup import DerivedUnit # {http://www.opengis.net/gml/3.2}DerivedUnit
from _nsgroup import ConventionalUnit # {http://www.opengis.net/gml/3.2}ConventionalUnit
from _nsgroup import CategoryExtent # {http://www.opengis.net/gml/3.2}CategoryExtent
from _nsgroup import QuantityExtent # {http://www.opengis.net/gml/3.2}QuantityExtent
from _nsgroup import AbstractGeneralConversion # {http://www.opengis.net/gml/3.2}AbstractGeneralConversion
from _nsgroup import AbstractGeneralTransformation # {http://www.opengis.net/gml/3.2}AbstractGeneralTransformation
from _nsgroup import ConcatenatedOperation # {http://www.opengis.net/gml/3.2}ConcatenatedOperation
from _nsgroup import PassThroughOperation # {http://www.opengis.net/gml/3.2}PassThroughOperation
from _nsgroup import OperationParameter # {http://www.opengis.net/gml/3.2}OperationParameter
from _nsgroup import OperationParameterGroup # {http://www.opengis.net/gml/3.2}OperationParameterGroup
from _nsgroup import AbstractGeneralDerivedCRS # {http://www.opengis.net/gml/3.2}AbstractGeneralDerivedCRS
from _nsgroup import CompoundCRS # {http://www.opengis.net/gml/3.2}CompoundCRS
from _nsgroup import GeodeticCRS # {http://www.opengis.net/gml/3.2}GeodeticCRS
from _nsgroup import VerticalCRS # {http://www.opengis.net/gml/3.2}VerticalCRS
from _nsgroup import EngineeringCRS # {http://www.opengis.net/gml/3.2}EngineeringCRS
from _nsgroup import ImageCRS # {http://www.opengis.net/gml/3.2}ImageCRS
from _nsgroup import TemporalCRS # {http://www.opengis.net/gml/3.2}TemporalCRS
from _nsgroup import EllipsoidalCS # {http://www.opengis.net/gml/3.2}EllipsoidalCS
from _nsgroup import CartesianCS # {http://www.opengis.net/gml/3.2}CartesianCS
from _nsgroup import VerticalCS # {http://www.opengis.net/gml/3.2}VerticalCS
from _nsgroup import TimeCS # {http://www.opengis.net/gml/3.2}TimeCS
from _nsgroup import LinearCS # {http://www.opengis.net/gml/3.2}LinearCS
from _nsgroup import UserDefinedCS # {http://www.opengis.net/gml/3.2}UserDefinedCS
from _nsgroup import SphericalCS # {http://www.opengis.net/gml/3.2}SphericalCS
from _nsgroup import PolarCS # {http://www.opengis.net/gml/3.2}PolarCS
from _nsgroup import CylindricalCS # {http://www.opengis.net/gml/3.2}CylindricalCS
from _nsgroup import AffineCS # {http://www.opengis.net/gml/3.2}AffineCS
from _nsgroup import GeodeticDatum # {http://www.opengis.net/gml/3.2}GeodeticDatum
from _nsgroup import EngineeringDatum # {http://www.opengis.net/gml/3.2}EngineeringDatum
from _nsgroup import ImageDatum # {http://www.opengis.net/gml/3.2}ImageDatum
from _nsgroup import VerticalDatum # {http://www.opengis.net/gml/3.2}VerticalDatum
from _nsgroup import TemporalCS # {http://www.opengis.net/gml/3.2}TemporalCS
from _nsgroup import ObliqueCartesianCS # {http://www.opengis.net/gml/3.2}ObliqueCartesianCS
from _nsgroup import GeographicCRS # {http://www.opengis.net/gml/3.2}GeographicCRS
from _nsgroup import GeocentricCRS # {http://www.opengis.net/gml/3.2}GeocentricCRS
from _nsgroup import Tin # {http://www.opengis.net/gml/3.2}Tin
from _nsgroup import Conversion # {http://www.opengis.net/gml/3.2}Conversion
from _nsgroup import Transformation # {http://www.opengis.net/gml/3.2}Transformation
from _nsgroup import ProjectedCRS # {http://www.opengis.net/gml/3.2}ProjectedCRS
from _nsgroup import DerivedCRS # {http://www.opengis.net/gml/3.2}DerivedCRS
from _nsgroup import TemporalDatum # {http://www.opengis.net/gml/3.2}TemporalDatum
from _nsgroup import STD_ANON # None
from _nsgroup import STD_ANON_ # None
from _nsgroup import SignType # {http://www.opengis.net/gml/3.2}SignType
from _nsgroup import CodeType # {http://www.opengis.net/gml/3.2}CodeType
from _nsgroup import STD_ANON_2 # None
from _nsgroup import UomSymbol # {http://www.opengis.net/gml/3.2}UomSymbol
from _nsgroup import UomURI # {http://www.opengis.net/gml/3.2}UomURI
from _nsgroup import CoordinatesType # {http://www.opengis.net/gml/3.2}CoordinatesType
from _nsgroup import booleanList # {http://www.opengis.net/gml/3.2}booleanList
from _nsgroup import doubleList # {http://www.opengis.net/gml/3.2}doubleList
from _nsgroup import integerList # {http://www.opengis.net/gml/3.2}integerList
from _nsgroup import NameList # {http://www.opengis.net/gml/3.2}NameList
from _nsgroup import NCNameList # {http://www.opengis.net/gml/3.2}NCNameList
from _nsgroup import QNameList # {http://www.opengis.net/gml/3.2}QNameList
from _nsgroup import AbstractGeneralParameterValueType # {http://www.opengis.net/gml/3.2}AbstractGeneralParameterValueType
from _nsgroup import AbstractGeneralParameterValuePropertyType # {http://www.opengis.net/gml/3.2}AbstractGeneralParameterValuePropertyType
from _nsgroup import RangeSetType # {http://www.opengis.net/gml/3.2}RangeSetType
from _nsgroup import DataBlockType # {http://www.opengis.net/gml/3.2}DataBlockType
from _nsgroup import FileType # {http://www.opengis.net/gml/3.2}FileType
from _nsgroup import CoverageFunctionType # {http://www.opengis.net/gml/3.2}CoverageFunctionType
from _nsgroup import MappingRuleType # {http://www.opengis.net/gml/3.2}MappingRuleType
from _nsgroup import GridFunctionType # {http://www.opengis.net/gml/3.2}GridFunctionType
from _nsgroup import SequenceRuleEnumeration # {http://www.opengis.net/gml/3.2}SequenceRuleEnumeration
from _nsgroup import AxisDirection # {http://www.opengis.net/gml/3.2}AxisDirection
from _nsgroup import CTD_ANON # None
from _nsgroup import CTD_ANON_ # None
from _nsgroup import SuccessionType # {http://www.opengis.net/gml/3.2}SuccessionType
from _nsgroup import DMSAngleType # {http://www.opengis.net/gml/3.2}DMSAngleType
from _nsgroup import STD_ANON_3 # None
from _nsgroup import DegreeValueType # {http://www.opengis.net/gml/3.2}DegreeValueType
from _nsgroup import DecimalMinutesType # {http://www.opengis.net/gml/3.2}DecimalMinutesType
from _nsgroup import ArcMinutesType # {http://www.opengis.net/gml/3.2}ArcMinutesType
from _nsgroup import ArcSecondsType # {http://www.opengis.net/gml/3.2}ArcSecondsType
from _nsgroup import AngleChoiceType # {http://www.opengis.net/gml/3.2}AngleChoiceType
from _nsgroup import ArrayAssociationType # {http://www.opengis.net/gml/3.2}ArrayAssociationType
from _nsgroup import AbstractMetaDataType # {http://www.opengis.net/gml/3.2}AbstractMetaDataType
from _nsgroup import FeatureArrayPropertyType # {http://www.opengis.net/gml/3.2}FeatureArrayPropertyType
from _nsgroup import IndirectEntryType # {http://www.opengis.net/gml/3.2}IndirectEntryType
from _nsgroup import IncrementOrder # {http://www.opengis.net/gml/3.2}IncrementOrder
from _nsgroup import DirectionVectorType # {http://www.opengis.net/gml/3.2}DirectionVectorType
from _nsgroup import DirectionDescriptionType # {http://www.opengis.net/gml/3.2}DirectionDescriptionType
from _nsgroup import CompassPointEnumeration # {http://www.opengis.net/gml/3.2}CompassPointEnumeration
from _nsgroup import HistoryPropertyType # {http://www.opengis.net/gml/3.2}HistoryPropertyType
from _nsgroup import AbstractFeatureMemberType # {http://www.opengis.net/gml/3.2}AbstractFeatureMemberType
from _nsgroup import GeometryArrayPropertyType # {http://www.opengis.net/gml/3.2}GeometryArrayPropertyType
from _nsgroup import PointArrayPropertyType # {http://www.opengis.net/gml/3.2}PointArrayPropertyType
from _nsgroup import CurveArrayPropertyType # {http://www.opengis.net/gml/3.2}CurveArrayPropertyType
from _nsgroup import SurfaceArrayPropertyType # {http://www.opengis.net/gml/3.2}SurfaceArrayPropertyType
from _nsgroup import AbstractRingType # {http://www.opengis.net/gml/3.2}AbstractRingType
from _nsgroup import AbstractRingPropertyType # {http://www.opengis.net/gml/3.2}AbstractRingPropertyType
from _nsgroup import LinearRingPropertyType # {http://www.opengis.net/gml/3.2}LinearRingPropertyType
from _nsgroup import AbstractCurveSegmentType # {http://www.opengis.net/gml/3.2}AbstractCurveSegmentType
from _nsgroup import CurveSegmentArrayPropertyType # {http://www.opengis.net/gml/3.2}CurveSegmentArrayPropertyType
from _nsgroup import CurveInterpolationType # {http://www.opengis.net/gml/3.2}CurveInterpolationType
from _nsgroup import KnotType # {http://www.opengis.net/gml/3.2}KnotType
from _nsgroup import KnotPropertyType # {http://www.opengis.net/gml/3.2}KnotPropertyType
from _nsgroup import KnotTypesType # {http://www.opengis.net/gml/3.2}KnotTypesType
from _nsgroup import AffinePlacementType # {http://www.opengis.net/gml/3.2}AffinePlacementType
from _nsgroup import CTD_ANON_2 # None
from _nsgroup import AbstractSurfacePatchType # {http://www.opengis.net/gml/3.2}AbstractSurfacePatchType
from _nsgroup import SurfacePatchArrayPropertyType # {http://www.opengis.net/gml/3.2}SurfacePatchArrayPropertyType
from _nsgroup import SurfaceInterpolationType # {http://www.opengis.net/gml/3.2}SurfaceInterpolationType
from _nsgroup import RingPropertyType # {http://www.opengis.net/gml/3.2}RingPropertyType
from _nsgroup import CTD_ANON_3 # None
from _nsgroup import CTD_ANON_4 # None
from _nsgroup import CTD_ANON_5 # None
from _nsgroup import LineStringSegmentArrayPropertyType # {http://www.opengis.net/gml/3.2}LineStringSegmentArrayPropertyType
from _nsgroup import SolidArrayPropertyType # {http://www.opengis.net/gml/3.2}SolidArrayPropertyType
from _nsgroup import ShellPropertyType # {http://www.opengis.net/gml/3.2}ShellPropertyType
from _nsgroup import AbstractGMLType # {http://www.opengis.net/gml/3.2}AbstractGMLType
from _nsgroup import InlinePropertyType # {http://www.opengis.net/gml/3.2}InlinePropertyType
from _nsgroup import AbstractMemberType # {http://www.opengis.net/gml/3.2}AbstractMemberType
from _nsgroup import AggregationType # {http://www.opengis.net/gml/3.2}AggregationType
from _nsgroup import AbstractMetadataPropertyType # {http://www.opengis.net/gml/3.2}AbstractMetadataPropertyType
from _nsgroup import GridLimitsType # {http://www.opengis.net/gml/3.2}GridLimitsType
from _nsgroup import GridEnvelopeType # {http://www.opengis.net/gml/3.2}GridEnvelopeType
from _nsgroup import STD_ANON_4 # None
from _nsgroup import TimeIndeterminateValueType # {http://www.opengis.net/gml/3.2}TimeIndeterminateValueType
from _nsgroup import TimePositionUnion # {http://www.opengis.net/gml/3.2}TimePositionUnion
from _nsgroup import CalDate # {http://www.opengis.net/gml/3.2}CalDate
from _nsgroup import STD_ANON_5 # None
from _nsgroup import STD_ANON_6 # None
from _nsgroup import TopoPointPropertyType # {http://www.opengis.net/gml/3.2}TopoPointPropertyType
from _nsgroup import TopoCurvePropertyType # {http://www.opengis.net/gml/3.2}TopoCurvePropertyType
from _nsgroup import TopoSurfacePropertyType # {http://www.opengis.net/gml/3.2}TopoSurfacePropertyType
from _nsgroup import TopoVolumePropertyType # {http://www.opengis.net/gml/3.2}TopoVolumePropertyType
from _nsgroup import TopoPrimitiveArrayAssociationType # {http://www.opengis.net/gml/3.2}TopoPrimitiveArrayAssociationType
from _nsgroup import FormulaType # {http://www.opengis.net/gml/3.2}FormulaType
from _nsgroup import ValueArrayPropertyType # {http://www.opengis.net/gml/3.2}ValueArrayPropertyType
from _nsgroup import NilReasonType # {http://www.opengis.net/gml/3.2}NilReasonType
from _nsgroup import NilReasonEnumeration # {http://www.opengis.net/gml/3.2}NilReasonEnumeration
from _nsgroup import booleanOrNilReason # {http://www.opengis.net/gml/3.2}booleanOrNilReason
from _nsgroup import doubleOrNilReason # {http://www.opengis.net/gml/3.2}doubleOrNilReason
from _nsgroup import integerOrNilReason # {http://www.opengis.net/gml/3.2}integerOrNilReason
from _nsgroup import NameOrNilReason # {http://www.opengis.net/gml/3.2}NameOrNilReason
from _nsgroup import stringOrNilReason # {http://www.opengis.net/gml/3.2}stringOrNilReason
from _nsgroup import CodeWithAuthorityType # {http://www.opengis.net/gml/3.2}CodeWithAuthorityType
from _nsgroup import UomIdentifier # {http://www.opengis.net/gml/3.2}UomIdentifier
from _nsgroup import CodeListType # {http://www.opengis.net/gml/3.2}CodeListType
from _nsgroup import ParameterValueType # {http://www.opengis.net/gml/3.2}ParameterValueType
from _nsgroup import ParameterValueGroupType # {http://www.opengis.net/gml/3.2}ParameterValueGroupType
from _nsgroup import AxisDirectionList # {http://www.opengis.net/gml/3.2}AxisDirectionList
from _nsgroup import DegreesType # {http://www.opengis.net/gml/3.2}DegreesType
from _nsgroup import BagType # {http://www.opengis.net/gml/3.2}BagType
from _nsgroup import ArrayType # {http://www.opengis.net/gml/3.2}ArrayType
from _nsgroup import GenericMetaDataType # {http://www.opengis.net/gml/3.2}GenericMetaDataType
from _nsgroup import DefinitionBaseType # {http://www.opengis.net/gml/3.2}DefinitionBaseType
from _nsgroup import AbstractTimeSliceType # {http://www.opengis.net/gml/3.2}AbstractTimeSliceType
from _nsgroup import AbstractFeatureType # {http://www.opengis.net/gml/3.2}AbstractFeatureType
from _nsgroup import AbstractGeometryType # {http://www.opengis.net/gml/3.2}AbstractGeometryType
from _nsgroup import DirectPositionType # {http://www.opengis.net/gml/3.2}DirectPositionType
from _nsgroup import DirectPositionListType # {http://www.opengis.net/gml/3.2}DirectPositionListType
from _nsgroup import STD_ANON_7 # None
from _nsgroup import EnvelopeType # {http://www.opengis.net/gml/3.2}EnvelopeType
from _nsgroup import LinearRingType # {http://www.opengis.net/gml/3.2}LinearRingType
from _nsgroup import LineStringSegmentType # {http://www.opengis.net/gml/3.2}LineStringSegmentType
from _nsgroup import ArcStringType # {http://www.opengis.net/gml/3.2}ArcStringType
from _nsgroup import ArcStringByBulgeType # {http://www.opengis.net/gml/3.2}ArcStringByBulgeType
from _nsgroup import ArcByCenterPointType # {http://www.opengis.net/gml/3.2}ArcByCenterPointType
from _nsgroup import CubicSplineType # {http://www.opengis.net/gml/3.2}CubicSplineType
from _nsgroup import BSplineType # {http://www.opengis.net/gml/3.2}BSplineType
from _nsgroup import OffsetCurveType # {http://www.opengis.net/gml/3.2}OffsetCurveType
from _nsgroup import ClothoidType # {http://www.opengis.net/gml/3.2}ClothoidType
from _nsgroup import GeodesicStringType # {http://www.opengis.net/gml/3.2}GeodesicStringType
from _nsgroup import PolygonPatchType # {http://www.opengis.net/gml/3.2}PolygonPatchType
from _nsgroup import TriangleType # {http://www.opengis.net/gml/3.2}TriangleType
from _nsgroup import RectangleType # {http://www.opengis.net/gml/3.2}RectangleType
from _nsgroup import RingType # {http://www.opengis.net/gml/3.2}RingType
from _nsgroup import AbstractParametricCurveSurfaceType # {http://www.opengis.net/gml/3.2}AbstractParametricCurveSurfaceType
from _nsgroup import ShellType # {http://www.opengis.net/gml/3.2}ShellType
from _nsgroup import AbstractTimeObjectType # {http://www.opengis.net/gml/3.2}AbstractTimeObjectType
from _nsgroup import TimePositionType # {http://www.opengis.net/gml/3.2}TimePositionType
from _nsgroup import TimeUnitType # {http://www.opengis.net/gml/3.2}TimeUnitType
from _nsgroup import AbstractTopologyType # {http://www.opengis.net/gml/3.2}AbstractTopologyType
from _nsgroup import CompositeValueType # {http://www.opengis.net/gml/3.2}CompositeValueType
from _nsgroup import MeasureType # {http://www.opengis.net/gml/3.2}MeasureType
from _nsgroup import booleanOrNilReasonList # {http://www.opengis.net/gml/3.2}booleanOrNilReasonList
from _nsgroup import NameOrNilReasonList # {http://www.opengis.net/gml/3.2}NameOrNilReasonList
from _nsgroup import doubleOrNilReasonList # {http://www.opengis.net/gml/3.2}doubleOrNilReasonList
from _nsgroup import integerOrNilReasonList # {http://www.opengis.net/gml/3.2}integerOrNilReasonList
from _nsgroup import MeasureListType # {http://www.opengis.net/gml/3.2}MeasureListType
from _nsgroup import CTD_ANON_6 # None
from _nsgroup import CoordinateOperationPropertyType # {http://www.opengis.net/gml/3.2}CoordinateOperationPropertyType
from _nsgroup import SingleOperationPropertyType # {http://www.opengis.net/gml/3.2}SingleOperationPropertyType
from _nsgroup import GeneralConversionPropertyType # {http://www.opengis.net/gml/3.2}GeneralConversionPropertyType
from _nsgroup import GeneralTransformationPropertyType # {http://www.opengis.net/gml/3.2}GeneralTransformationPropertyType
from _nsgroup import ConcatenatedOperationPropertyType # {http://www.opengis.net/gml/3.2}ConcatenatedOperationPropertyType
from _nsgroup import PassThroughOperationPropertyType # {http://www.opengis.net/gml/3.2}PassThroughOperationPropertyType
from _nsgroup import ConversionPropertyType # {http://www.opengis.net/gml/3.2}ConversionPropertyType
from _nsgroup import TransformationPropertyType # {http://www.opengis.net/gml/3.2}TransformationPropertyType
from _nsgroup import CTD_ANON_7 # None
from _nsgroup import OperationMethodPropertyType # {http://www.opengis.net/gml/3.2}OperationMethodPropertyType
from _nsgroup import AbstractGeneralOperationParameterPropertyType # {http://www.opengis.net/gml/3.2}AbstractGeneralOperationParameterPropertyType
from _nsgroup import OperationParameterPropertyType # {http://www.opengis.net/gml/3.2}OperationParameterPropertyType
from _nsgroup import OperationParameterGroupPropertyType # {http://www.opengis.net/gml/3.2}OperationParameterGroupPropertyType
from _nsgroup import SingleCRSPropertyType # {http://www.opengis.net/gml/3.2}SingleCRSPropertyType
from _nsgroup import CompoundCRSPropertyType # {http://www.opengis.net/gml/3.2}CompoundCRSPropertyType
from _nsgroup import GeodeticCRSPropertyType # {http://www.opengis.net/gml/3.2}GeodeticCRSPropertyType
from _nsgroup import VerticalCRSPropertyType # {http://www.opengis.net/gml/3.2}VerticalCRSPropertyType
from _nsgroup import ProjectedCRSPropertyType # {http://www.opengis.net/gml/3.2}ProjectedCRSPropertyType
from _nsgroup import DerivedCRSPropertyType # {http://www.opengis.net/gml/3.2}DerivedCRSPropertyType
from _nsgroup import EngineeringCRSPropertyType # {http://www.opengis.net/gml/3.2}EngineeringCRSPropertyType
from _nsgroup import ImageCRSPropertyType # {http://www.opengis.net/gml/3.2}ImageCRSPropertyType
from _nsgroup import TemporalCRSPropertyType # {http://www.opengis.net/gml/3.2}TemporalCRSPropertyType
from _nsgroup import CoordinateSystemAxisPropertyType # {http://www.opengis.net/gml/3.2}CoordinateSystemAxisPropertyType
from _nsgroup import CoordinateSystemPropertyType # {http://www.opengis.net/gml/3.2}CoordinateSystemPropertyType
from _nsgroup import EllipsoidalCSPropertyType # {http://www.opengis.net/gml/3.2}EllipsoidalCSPropertyType
from _nsgroup import CartesianCSPropertyType # {http://www.opengis.net/gml/3.2}CartesianCSPropertyType
from _nsgroup import VerticalCSPropertyType # {http://www.opengis.net/gml/3.2}VerticalCSPropertyType
from _nsgroup import TimeCSPropertyType # {http://www.opengis.net/gml/3.2}TimeCSPropertyType
from _nsgroup import LinearCSPropertyType # {http://www.opengis.net/gml/3.2}LinearCSPropertyType
from _nsgroup import UserDefinedCSPropertyType # {http://www.opengis.net/gml/3.2}UserDefinedCSPropertyType
from _nsgroup import SphericalCSPropertyType # {http://www.opengis.net/gml/3.2}SphericalCSPropertyType
from _nsgroup import PolarCSPropertyType # {http://www.opengis.net/gml/3.2}PolarCSPropertyType
from _nsgroup import CylindricalCSPropertyType # {http://www.opengis.net/gml/3.2}CylindricalCSPropertyType
from _nsgroup import AffineCSPropertyType # {http://www.opengis.net/gml/3.2}AffineCSPropertyType
from _nsgroup import AbstractCoverageType # {http://www.opengis.net/gml/3.2}AbstractCoverageType
from _nsgroup import DomainSetType # {http://www.opengis.net/gml/3.2}DomainSetType
from _nsgroup import SequenceRuleType # {http://www.opengis.net/gml/3.2}SequenceRuleType
from _nsgroup import DatumPropertyType # {http://www.opengis.net/gml/3.2}DatumPropertyType
from _nsgroup import GeodeticDatumPropertyType # {http://www.opengis.net/gml/3.2}GeodeticDatumPropertyType
from _nsgroup import EllipsoidPropertyType # {http://www.opengis.net/gml/3.2}EllipsoidPropertyType
from _nsgroup import PrimeMeridianPropertyType # {http://www.opengis.net/gml/3.2}PrimeMeridianPropertyType
from _nsgroup import EngineeringDatumPropertyType # {http://www.opengis.net/gml/3.2}EngineeringDatumPropertyType
from _nsgroup import ImageDatumPropertyType # {http://www.opengis.net/gml/3.2}ImageDatumPropertyType
from _nsgroup import VerticalDatumPropertyType # {http://www.opengis.net/gml/3.2}VerticalDatumPropertyType
from _nsgroup import TemporalDatumPropertyType # {http://www.opengis.net/gml/3.2}TemporalDatumPropertyType
from _nsgroup import OperationPropertyType # {http://www.opengis.net/gml/3.2}OperationPropertyType
from _nsgroup import TemporalCSPropertyType # {http://www.opengis.net/gml/3.2}TemporalCSPropertyType
from _nsgroup import ObliqueCartesianCSPropertyType # {http://www.opengis.net/gml/3.2}ObliqueCartesianCSPropertyType
from _nsgroup import GeographicCRSPropertyType # {http://www.opengis.net/gml/3.2}GeographicCRSPropertyType
from _nsgroup import GeocentricCRSPropertyType # {http://www.opengis.net/gml/3.2}GeocentricCRSPropertyType
from _nsgroup import StringOrRefType # {http://www.opengis.net/gml/3.2}StringOrRefType
from _nsgroup import MetaDataPropertyType # {http://www.opengis.net/gml/3.2}MetaDataPropertyType
from _nsgroup import LocationPropertyType # {http://www.opengis.net/gml/3.2}LocationPropertyType
from _nsgroup import BoundedFeatureType # {http://www.opengis.net/gml/3.2}BoundedFeatureType
from _nsgroup import AbstractFeatureCollectionType # {http://www.opengis.net/gml/3.2}AbstractFeatureCollectionType
from _nsgroup import MovingObjectStatusType # {http://www.opengis.net/gml/3.2}MovingObjectStatusType
from _nsgroup import DefinitionType # {http://www.opengis.net/gml/3.2}DefinitionType
from _nsgroup import DictionaryEntryType # {http://www.opengis.net/gml/3.2}DictionaryEntryType
from _nsgroup import DirectionPropertyType # {http://www.opengis.net/gml/3.2}DirectionPropertyType
from _nsgroup import DynamicFeatureType # {http://www.opengis.net/gml/3.2}DynamicFeatureType
from _nsgroup import DynamicFeatureMemberType # {http://www.opengis.net/gml/3.2}DynamicFeatureMemberType
from _nsgroup import FeaturePropertyType # {http://www.opengis.net/gml/3.2}FeaturePropertyType
from _nsgroup import BoundingShapeType # {http://www.opengis.net/gml/3.2}BoundingShapeType
from _nsgroup import EnvelopeWithTimePeriodType # {http://www.opengis.net/gml/3.2}EnvelopeWithTimePeriodType
from _nsgroup import AbstractGeometricAggregateType # {http://www.opengis.net/gml/3.2}AbstractGeometricAggregateType
from _nsgroup import MultiGeometryPropertyType # {http://www.opengis.net/gml/3.2}MultiGeometryPropertyType
from _nsgroup import MultiPointPropertyType # {http://www.opengis.net/gml/3.2}MultiPointPropertyType
from _nsgroup import MultiCurvePropertyType # {http://www.opengis.net/gml/3.2}MultiCurvePropertyType
from _nsgroup import MultiSurfacePropertyType # {http://www.opengis.net/gml/3.2}MultiSurfacePropertyType
from _nsgroup import MultiSolidPropertyType # {http://www.opengis.net/gml/3.2}MultiSolidPropertyType
from _nsgroup import GeometryPropertyType # {http://www.opengis.net/gml/3.2}GeometryPropertyType
from _nsgroup import VectorType # {http://www.opengis.net/gml/3.2}VectorType
from _nsgroup import AbstractGeometricPrimitiveType # {http://www.opengis.net/gml/3.2}AbstractGeometricPrimitiveType
from _nsgroup import GeometricPrimitivePropertyType # {http://www.opengis.net/gml/3.2}GeometricPrimitivePropertyType
from _nsgroup import PointPropertyType # {http://www.opengis.net/gml/3.2}PointPropertyType
from _nsgroup import CurvePropertyType # {http://www.opengis.net/gml/3.2}CurvePropertyType
from _nsgroup import SurfacePropertyType # {http://www.opengis.net/gml/3.2}SurfacePropertyType
from _nsgroup import GeometricComplexType # {http://www.opengis.net/gml/3.2}GeometricComplexType
from _nsgroup import GeometricComplexPropertyType # {http://www.opengis.net/gml/3.2}GeometricComplexPropertyType
from _nsgroup import ArcType # {http://www.opengis.net/gml/3.2}ArcType
from _nsgroup import ArcByBulgeType # {http://www.opengis.net/gml/3.2}ArcByBulgeType
from _nsgroup import CircleByCenterPointType # {http://www.opengis.net/gml/3.2}CircleByCenterPointType
from _nsgroup import BezierType # {http://www.opengis.net/gml/3.2}BezierType
from _nsgroup import GeodesicType # {http://www.opengis.net/gml/3.2}GeodesicType
from _nsgroup import AbstractGriddedSurfaceType # {http://www.opengis.net/gml/3.2}AbstractGriddedSurfaceType
from _nsgroup import SolidPropertyType # {http://www.opengis.net/gml/3.2}SolidPropertyType
from _nsgroup import AssociationRoleType # {http://www.opengis.net/gml/3.2}AssociationRoleType
from _nsgroup import ReferenceType # {http://www.opengis.net/gml/3.2}ReferenceType
from _nsgroup import GridType # {http://www.opengis.net/gml/3.2}GridType
from _nsgroup import ObservationType # {http://www.opengis.net/gml/3.2}ObservationType
from _nsgroup import ProcedurePropertyType # {http://www.opengis.net/gml/3.2}ProcedurePropertyType
from _nsgroup import TargetPropertyType # {http://www.opengis.net/gml/3.2}TargetPropertyType
from _nsgroup import ResultType # {http://www.opengis.net/gml/3.2}ResultType
from _nsgroup import CTD_ANON_8 # None
from _nsgroup import CRSPropertyType # {http://www.opengis.net/gml/3.2}CRSPropertyType
from _nsgroup import AbstractTimePrimitiveType # {http://www.opengis.net/gml/3.2}AbstractTimePrimitiveType
from _nsgroup import TimePrimitivePropertyType # {http://www.opengis.net/gml/3.2}TimePrimitivePropertyType
from _nsgroup import AbstractTimeComplexType # {http://www.opengis.net/gml/3.2}AbstractTimeComplexType
from _nsgroup import TimeInstantPropertyType # {http://www.opengis.net/gml/3.2}TimeInstantPropertyType
from _nsgroup import TimePeriodPropertyType # {http://www.opengis.net/gml/3.2}TimePeriodPropertyType
from _nsgroup import TimeIntervalLengthType # {http://www.opengis.net/gml/3.2}TimeIntervalLengthType
from _nsgroup import TimeCalendarPropertyType # {http://www.opengis.net/gml/3.2}TimeCalendarPropertyType
from _nsgroup import TimeCalendarEraPropertyType # {http://www.opengis.net/gml/3.2}TimeCalendarEraPropertyType
from _nsgroup import TimeClockPropertyType # {http://www.opengis.net/gml/3.2}TimeClockPropertyType
from _nsgroup import TimeOrdinalEraPropertyType # {http://www.opengis.net/gml/3.2}TimeOrdinalEraPropertyType
from _nsgroup import TimeTopologyPrimitivePropertyType # {http://www.opengis.net/gml/3.2}TimeTopologyPrimitivePropertyType
from _nsgroup import TimeTopologyComplexPropertyType # {http://www.opengis.net/gml/3.2}TimeTopologyComplexPropertyType
from _nsgroup import TimeNodePropertyType # {http://www.opengis.net/gml/3.2}TimeNodePropertyType
from _nsgroup import TimeEdgePropertyType # {http://www.opengis.net/gml/3.2}TimeEdgePropertyType
from _nsgroup import AbstractTopoPrimitiveType # {http://www.opengis.net/gml/3.2}AbstractTopoPrimitiveType
from _nsgroup import NodeOrEdgePropertyType # {http://www.opengis.net/gml/3.2}NodeOrEdgePropertyType
from _nsgroup import NodePropertyType # {http://www.opengis.net/gml/3.2}NodePropertyType
from _nsgroup import FaceOrTopoSolidPropertyType # {http://www.opengis.net/gml/3.2}FaceOrTopoSolidPropertyType
from _nsgroup import TopoSolidPropertyType # {http://www.opengis.net/gml/3.2}TopoSolidPropertyType
from _nsgroup import DirectedNodePropertyType # {http://www.opengis.net/gml/3.2}DirectedNodePropertyType
from _nsgroup import DirectedEdgePropertyType # {http://www.opengis.net/gml/3.2}DirectedEdgePropertyType
from _nsgroup import DirectedFacePropertyType # {http://www.opengis.net/gml/3.2}DirectedFacePropertyType
from _nsgroup import DirectedTopoSolidPropertyType # {http://www.opengis.net/gml/3.2}DirectedTopoSolidPropertyType
from _nsgroup import TopoPointType # {http://www.opengis.net/gml/3.2}TopoPointType
from _nsgroup import TopoCurveType # {http://www.opengis.net/gml/3.2}TopoCurveType
from _nsgroup import TopoSurfaceType # {http://www.opengis.net/gml/3.2}TopoSurfaceType
from _nsgroup import TopoVolumeType # {http://www.opengis.net/gml/3.2}TopoVolumeType
from _nsgroup import TopoComplexType # {http://www.opengis.net/gml/3.2}TopoComplexType
from _nsgroup import TopoPrimitiveMemberType # {http://www.opengis.net/gml/3.2}TopoPrimitiveMemberType
from _nsgroup import TopoComplexPropertyType # {http://www.opengis.net/gml/3.2}TopoComplexPropertyType
from _nsgroup import UnitOfMeasureType # {http://www.opengis.net/gml/3.2}UnitOfMeasureType
from _nsgroup import CTD_ANON_9 # None
from _nsgroup import CTD_ANON_10 # None
from _nsgroup import CTD_ANON_11 # None
from _nsgroup import ValuePropertyType # {http://www.opengis.net/gml/3.2}ValuePropertyType
from _nsgroup import ValueArrayType # {http://www.opengis.net/gml/3.2}ValueArrayType
from _nsgroup import BooleanPropertyType # {http://www.opengis.net/gml/3.2}BooleanPropertyType
from _nsgroup import CategoryPropertyType # {http://www.opengis.net/gml/3.2}CategoryPropertyType
from _nsgroup import QuantityPropertyType # {http://www.opengis.net/gml/3.2}QuantityPropertyType
from _nsgroup import CountPropertyType # {http://www.opengis.net/gml/3.2}CountPropertyType
from _nsgroup import CodeOrNilReasonListType # {http://www.opengis.net/gml/3.2}CodeOrNilReasonListType
from _nsgroup import MeasureOrNilReasonListType # {http://www.opengis.net/gml/3.2}MeasureOrNilReasonListType
from _nsgroup import DiscreteCoverageType # {http://www.opengis.net/gml/3.2}DiscreteCoverageType
from _nsgroup import AbstractContinuousCoverageType # {http://www.opengis.net/gml/3.2}AbstractContinuousCoverageType
from _nsgroup import PriorityLocationPropertyType # {http://www.opengis.net/gml/3.2}PriorityLocationPropertyType
from _nsgroup import FeatureCollectionType # {http://www.opengis.net/gml/3.2}FeatureCollectionType
from _nsgroup import DefinitionProxyType # {http://www.opengis.net/gml/3.2}DefinitionProxyType
from _nsgroup import DictionaryType # {http://www.opengis.net/gml/3.2}DictionaryType
from _nsgroup import DynamicFeatureCollectionType # {http://www.opengis.net/gml/3.2}DynamicFeatureCollectionType
from _nsgroup import MultiGeometryType # {http://www.opengis.net/gml/3.2}MultiGeometryType
from _nsgroup import MultiPointType # {http://www.opengis.net/gml/3.2}MultiPointType
from _nsgroup import MultiCurveType # {http://www.opengis.net/gml/3.2}MultiCurveType
from _nsgroup import MultiSurfaceType # {http://www.opengis.net/gml/3.2}MultiSurfaceType
from _nsgroup import MultiSolidType # {http://www.opengis.net/gml/3.2}MultiSolidType
from _nsgroup import PointType # {http://www.opengis.net/gml/3.2}PointType
from _nsgroup import AbstractCurveType # {http://www.opengis.net/gml/3.2}AbstractCurveType
from _nsgroup import AbstractSurfaceType # {http://www.opengis.net/gml/3.2}AbstractSurfaceType
from _nsgroup import CircleType # {http://www.opengis.net/gml/3.2}CircleType
from _nsgroup import ConeType # {http://www.opengis.net/gml/3.2}ConeType
from _nsgroup import CylinderType # {http://www.opengis.net/gml/3.2}CylinderType
from _nsgroup import SphereType # {http://www.opengis.net/gml/3.2}SphereType
from _nsgroup import AbstractSolidType # {http://www.opengis.net/gml/3.2}AbstractSolidType
from _nsgroup import RectifiedGridType # {http://www.opengis.net/gml/3.2}RectifiedGridType
from _nsgroup import LengthType # {http://www.opengis.net/gml/3.2}LengthType
from _nsgroup import ScaleType # {http://www.opengis.net/gml/3.2}ScaleType
from _nsgroup import TimeType # {http://www.opengis.net/gml/3.2}TimeType
from _nsgroup import GridLengthType # {http://www.opengis.net/gml/3.2}GridLengthType
from _nsgroup import AreaType # {http://www.opengis.net/gml/3.2}AreaType
from _nsgroup import VolumeType # {http://www.opengis.net/gml/3.2}VolumeType
from _nsgroup import SpeedType # {http://www.opengis.net/gml/3.2}SpeedType
from _nsgroup import AngleType # {http://www.opengis.net/gml/3.2}AngleType
from _nsgroup import DirectedObservationType # {http://www.opengis.net/gml/3.2}DirectedObservationType
from _nsgroup import IdentifiedObjectType # {http://www.opengis.net/gml/3.2}IdentifiedObjectType
from _nsgroup import RelatedTimeType # {http://www.opengis.net/gml/3.2}RelatedTimeType
from _nsgroup import AbstractTimeGeometricPrimitiveType # {http://www.opengis.net/gml/3.2}AbstractTimeGeometricPrimitiveType
from _nsgroup import TimeReferenceSystemType # {http://www.opengis.net/gml/3.2}TimeReferenceSystemType
from _nsgroup import TimeCalendarEraType # {http://www.opengis.net/gml/3.2}TimeCalendarEraType
from _nsgroup import TimeOrdinalEraType # {http://www.opengis.net/gml/3.2}TimeOrdinalEraType
from _nsgroup import AbstractTimeTopologyPrimitiveType # {http://www.opengis.net/gml/3.2}AbstractTimeTopologyPrimitiveType
from _nsgroup import TimeTopologyComplexType # {http://www.opengis.net/gml/3.2}TimeTopologyComplexType
from _nsgroup import NodeType # {http://www.opengis.net/gml/3.2}NodeType
from _nsgroup import EdgeType # {http://www.opengis.net/gml/3.2}EdgeType
from _nsgroup import FaceType # {http://www.opengis.net/gml/3.2}FaceType
from _nsgroup import TopoSolidType # {http://www.opengis.net/gml/3.2}TopoSolidType
from _nsgroup import UnitDefinitionType # {http://www.opengis.net/gml/3.2}UnitDefinitionType
from _nsgroup import DerivationUnitTermType # {http://www.opengis.net/gml/3.2}DerivationUnitTermType
from _nsgroup import ConversionToPreferredUnitType # {http://www.opengis.net/gml/3.2}ConversionToPreferredUnitType
from _nsgroup import CTD_ANON_12 # None
from _nsgroup import STD_ANON_8 # None
from _nsgroup import CountExtentType # {http://www.opengis.net/gml/3.2}CountExtentType
from _nsgroup import STD_ANON_9 # None
from _nsgroup import AbstractCoordinateOperationType # {http://www.opengis.net/gml/3.2}AbstractCoordinateOperationType
from _nsgroup import OperationMethodType # {http://www.opengis.net/gml/3.2}OperationMethodType
from _nsgroup import AbstractGeneralOperationParameterType # {http://www.opengis.net/gml/3.2}AbstractGeneralOperationParameterType
from _nsgroup import CoordinateSystemAxisType # {http://www.opengis.net/gml/3.2}CoordinateSystemAxisType
from _nsgroup import AbstractCoordinateSystemType # {http://www.opengis.net/gml/3.2}AbstractCoordinateSystemType
from _nsgroup import AbstractDatumType # {http://www.opengis.net/gml/3.2}AbstractDatumType
from _nsgroup import EllipsoidType # {http://www.opengis.net/gml/3.2}EllipsoidType
from _nsgroup import PrimeMeridianType # {http://www.opengis.net/gml/3.2}PrimeMeridianType
from _nsgroup import LineStringType # {http://www.opengis.net/gml/3.2}LineStringType
from _nsgroup import PolygonType # {http://www.opengis.net/gml/3.2}PolygonType
from _nsgroup import CompositeCurveType # {http://www.opengis.net/gml/3.2}CompositeCurveType
from _nsgroup import CompositeSurfaceType # {http://www.opengis.net/gml/3.2}CompositeSurfaceType
from _nsgroup import CompositeSolidType # {http://www.opengis.net/gml/3.2}CompositeSolidType
from _nsgroup import CurveType # {http://www.opengis.net/gml/3.2}CurveType
from _nsgroup import OrientableCurveType # {http://www.opengis.net/gml/3.2}OrientableCurveType
from _nsgroup import SurfaceType # {http://www.opengis.net/gml/3.2}SurfaceType
from _nsgroup import OrientableSurfaceType # {http://www.opengis.net/gml/3.2}OrientableSurfaceType
from _nsgroup import SolidType # {http://www.opengis.net/gml/3.2}SolidType
from _nsgroup import DirectedObservationAtDistanceType # {http://www.opengis.net/gml/3.2}DirectedObservationAtDistanceType
from _nsgroup import AbstractCRSType # {http://www.opengis.net/gml/3.2}AbstractCRSType
from _nsgroup import TimeInstantType # {http://www.opengis.net/gml/3.2}TimeInstantType
from _nsgroup import TimePeriodType # {http://www.opengis.net/gml/3.2}TimePeriodType
from _nsgroup import TimeCoordinateSystemType # {http://www.opengis.net/gml/3.2}TimeCoordinateSystemType
from _nsgroup import TimeCalendarType # {http://www.opengis.net/gml/3.2}TimeCalendarType
from _nsgroup import TimeClockType # {http://www.opengis.net/gml/3.2}TimeClockType
from _nsgroup import TimeOrdinalReferenceSystemType # {http://www.opengis.net/gml/3.2}TimeOrdinalReferenceSystemType
from _nsgroup import TimeNodeType # {http://www.opengis.net/gml/3.2}TimeNodeType
from _nsgroup import TimeEdgeType # {http://www.opengis.net/gml/3.2}TimeEdgeType
from _nsgroup import BaseUnitType # {http://www.opengis.net/gml/3.2}BaseUnitType
from _nsgroup import DerivedUnitType # {http://www.opengis.net/gml/3.2}DerivedUnitType
from _nsgroup import ConventionalUnitType # {http://www.opengis.net/gml/3.2}ConventionalUnitType
from _nsgroup import CategoryExtentType # {http://www.opengis.net/gml/3.2}CategoryExtentType
from _nsgroup import QuantityExtentType # {http://www.opengis.net/gml/3.2}QuantityExtentType
from _nsgroup import AbstractGeneralConversionType # {http://www.opengis.net/gml/3.2}AbstractGeneralConversionType
from _nsgroup import AbstractGeneralTransformationType # {http://www.opengis.net/gml/3.2}AbstractGeneralTransformationType
from _nsgroup import ConcatenatedOperationType # {http://www.opengis.net/gml/3.2}ConcatenatedOperationType
from _nsgroup import PassThroughOperationType # {http://www.opengis.net/gml/3.2}PassThroughOperationType
from _nsgroup import OperationParameterType # {http://www.opengis.net/gml/3.2}OperationParameterType
from _nsgroup import OperationParameterGroupType # {http://www.opengis.net/gml/3.2}OperationParameterGroupType
from _nsgroup import AbstractGeneralDerivedCRSType # {http://www.opengis.net/gml/3.2}AbstractGeneralDerivedCRSType
from _nsgroup import CompoundCRSType # {http://www.opengis.net/gml/3.2}CompoundCRSType
from _nsgroup import GeodeticCRSType # {http://www.opengis.net/gml/3.2}GeodeticCRSType
from _nsgroup import VerticalCRSType # {http://www.opengis.net/gml/3.2}VerticalCRSType
from _nsgroup import EngineeringCRSType # {http://www.opengis.net/gml/3.2}EngineeringCRSType
from _nsgroup import ImageCRSType # {http://www.opengis.net/gml/3.2}ImageCRSType
from _nsgroup import TemporalCRSType # {http://www.opengis.net/gml/3.2}TemporalCRSType
from _nsgroup import EllipsoidalCSType # {http://www.opengis.net/gml/3.2}EllipsoidalCSType
from _nsgroup import CartesianCSType # {http://www.opengis.net/gml/3.2}CartesianCSType
from _nsgroup import VerticalCSType # {http://www.opengis.net/gml/3.2}VerticalCSType
from _nsgroup import TimeCSType # {http://www.opengis.net/gml/3.2}TimeCSType
from _nsgroup import LinearCSType # {http://www.opengis.net/gml/3.2}LinearCSType
from _nsgroup import UserDefinedCSType # {http://www.opengis.net/gml/3.2}UserDefinedCSType
from _nsgroup import SphericalCSType # {http://www.opengis.net/gml/3.2}SphericalCSType
from _nsgroup import PolarCSType # {http://www.opengis.net/gml/3.2}PolarCSType
from _nsgroup import CylindricalCSType # {http://www.opengis.net/gml/3.2}CylindricalCSType
from _nsgroup import AffineCSType # {http://www.opengis.net/gml/3.2}AffineCSType
from _nsgroup import GeodeticDatumType # {http://www.opengis.net/gml/3.2}GeodeticDatumType
from _nsgroup import EngineeringDatumType # {http://www.opengis.net/gml/3.2}EngineeringDatumType
from _nsgroup import ImageDatumType # {http://www.opengis.net/gml/3.2}ImageDatumType
from _nsgroup import VerticalDatumType # {http://www.opengis.net/gml/3.2}VerticalDatumType
from _nsgroup import TemporalDatumBaseType # {http://www.opengis.net/gml/3.2}TemporalDatumBaseType
from _nsgroup import TemporalCSType # {http://www.opengis.net/gml/3.2}TemporalCSType
from _nsgroup import ObliqueCartesianCSType # {http://www.opengis.net/gml/3.2}ObliqueCartesianCSType
from _nsgroup import GeographicCRSType # {http://www.opengis.net/gml/3.2}GeographicCRSType
from _nsgroup import GeocentricCRSType # {http://www.opengis.net/gml/3.2}GeocentricCRSType
from _nsgroup import TinType # {http://www.opengis.net/gml/3.2}TinType
from _nsgroup import ConversionType # {http://www.opengis.net/gml/3.2}ConversionType
from _nsgroup import TransformationType # {http://www.opengis.net/gml/3.2}TransformationType
from _nsgroup import ProjectedCRSType # {http://www.opengis.net/gml/3.2}ProjectedCRSType
from _nsgroup import DerivedCRSType # {http://www.opengis.net/gml/3.2}DerivedCRSType
from _nsgroup import TemporalDatumType # {http://www.opengis.net/gml/3.2}TemporalDatumType
